### ISSUE TITLE
500 Unknown error on /v2/spaces/GUID/summary while apps are being deleted

### ISSUE THREAD

**Issue by tyyko** [cloudfoundry/cloud_controller_ng#1107]
## Issue

Call to `/v2/spaces/[GUID]/summary` returns a "500" Error `undefined method has_developer?' for nil:NilClass\` while applications of same space are being deleted.
This call is used in both 'cf apps' and 'cf services' CLI commands.

## Context

Most probably related to #799 and #717

On large systems we have are several applications being deployed or deleted in parallel. When this happen, we often see 500 errors from CC when listing applications or services in the same space.

## Steps to Reproduce

Push 200 apps to setup environment
```
for a in $( seq 200 ); do cf push testapp$a & done
wait
```

Start deleting the applications in background and at same time start calling /v2/spaces/GUID/summary trough cf cli 'cf a' command and save output.
```
APPLICATIONS=$(cf apps | tail -n +5 | awk '{print $1}')
for APPLICATION in $APPLICATIONS; do cf d -f "$APPLICATION" & done

export CF_TRACE=true
for a in $( seq 200 ); do cf a > output$a.log 2>&1 & done
sleep 5s
for a in $( seq 200 300 ); do cf a > output$a.log 2>&1 & done
```

Find errors
```
cat output* | grep " 500"
```

## Expected result

Never see an HTTP 500 error.

## Current result

From less then 10 to dozen of 500 errors.

Detailed error from CC logs:
```
{"timestamp":1520418057.8068683,"message":"Request failed: 500: {\"error_code\"=>\"UnknownError\", \"description\"=>\"An unknown error occurred.\", \"code\"=>10001, \"test_mode_info\"=>{\"description\"=>\"undefined method `has_developer?' for nil:NilClass\", \"error_code\"=>\"CF-has_developer?\", \"backtrace\"=>[\"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/app/access/process_model_access.rb:31:in `read_env?'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/allowy-2.1.0/lib/allowy/access_control.rb:74:in `block in check_permission'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/allowy-2.1.0/lib/allowy/access_control.rb:74:in `catch'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/allowy-2.1.0/lib/allowy/access_control.rb:74:in `check_permission'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/allowy-2.1.0/lib/allowy/access_control.rb:51:in `can?'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/allowy-2.1.0/lib/allowy/context.rb:35:in `can?'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/app/models/runtime/process_model.rb:524:in `to_hash'\", \"/var/vcap/data/packages/cloud_controller_ng/691a4762db30057a7bb0d73e354f611a311c6bb9/cloud_controller_ng/app/controllers/runtime/space_summaries_controller.rb:48:in `block in app_summary'\", \"/var/vcap/data/packages/cloud_controller_ng/691a4762db30057a7bb0d73e354f611a311c6bb9/cloud_controller_ng/app/controllers/runtime/space_summaries_controller.rb:40:in `collect'\", \"/var/vcap/data/packages/cloud_controller_ng/691a4762db30057a7bb0d73e354f611a311c6bb9/cloud_controller_ng/app/controllers/runtime/space_summaries_controller.rb:40:in `app_summary'\", \"/var/vcap/data/packages/cloud_controller_ng/691a4762db30057a7bb0d73e354f611a311c6bb9/cloud_controller_ng/app/controllers/runtime/space_summaries_controller.rb:33:in `space_summary'\", \"/var/vcap/data/packages/cloud_controller_ng/691a4762db30057a7bb0d73e354f611a311c6bb9/cloud_controller_ng/app/controllers/runtime/space_summaries_controller.rb:15:in `summary'\", \"/var/vcap/data/packages/cloud_controller_ng/691a4762db30057a7bb0d73e354f611a311c6bb9/cloud_controller_ng/app/controllers/base/base_controller.rb:79:in `dispatch'\", \"/var/vcap/data/packages/cloud_controller_ng/691a4762db30057a7bb0d73e354f611a311c6bb9/cloud_controller_ng/lib/cloud_controller/rest_controller/routes.rb:16:in `block in define_route'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1610:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1610:in `block in compile!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-1.6.8/lib/rack/nulllogger.rb:9:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-1.6.8/lib/rack/head.rb:13:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-1.6.8/lib/rack/urlmap.rb:66:in `block in call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `each'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/rate_limiter.rb:43:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/request_logs.rb:22:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/security_context_setter.rb:19:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/vcap_request_id.rb:15:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/cors.rb:49:in `call_app'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/cors.rb:14:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/request_metrics.rb:12:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-1.6.8/lib/rack/builder.rb:153:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/thin/connection.rb:86:in `block in pre_process'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `catch'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `pre_process'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/thin/connection.rb:50:in `block in process'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:1067:in `block in spawn_threadpool'\"]}}","log_level":"error","source":"cc.api","data":{"request_guid":"a66c9afa-386d-499d-51cc-01b4c530b6ee::0e2d29fe-a949-4c97-8d1a-7c5838e8cf2f"},"thread_id":47065291686840,"fiber_id":47065279327260,"process_id":23801,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/sinatra/vcap.rb","lineno":46,"method":"block in registered"}
{"timestamp":1520418057.807369,"message":"Completed 500 vcap-request-id: a66c9afa-386d-499d-51cc-01b4c530b6ee::0e2d29fe-a949-4c97-8d1a-7c5838e8cf2f","log_level":"info","source":"cc.api","data":{"request_guid":"a66c9afa-386d-499d-51cc-01b4c530b6ee::0e2d29fe-a949-4c97-8d1a-7c5838e8cf2f"},"thread_id":47065291686840,"fiber_id":47065279327260,"process_id":23801,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/request_logs.rb","lineno":24,"method":"call"}
```

**Comment by elenasharma** [comment]
Hello @tyyko, thanks for filing this bug with us.

We pushed 200 apps and then deleted them while hitting `/v2/spaces/:guid/summary`, as in your reproduction steps. We did not see any 500 errors in the output, or the undefined method `has_developer?` error in the CC logs.

What version of `capi-release` are you seeing this issue on?

**Comment by h0nIg** [comment]
@elenasharma did you executed the mentioned script or did you executed equal commands which "might" do the same? How many request did you fired against /v2/spaces/:guid/summary and how much time in between these requests?

**Comment by tyyko** [comment]
Hello, at the time we used CF deployment v1.15 so capi-release v1.49.0 and now we are on cf-deployment v1.12 and capi-release v1.52.0

**Comment by selzoc** [comment]
Hello @tyyko && @h0nIg 

We just pushed a commit that should solve this issue: 3ad8b5ea31023c372b7c2500e1f935df6b11dc39

Closing this, please let us know if you see this behavior after the next capi-release.

Thanks,
Chris && @ericpromislow
