### ISSUE TITLE
Migration retry should not fail

### ISSUE THREAD

**Issue by michelleheh** [cloudfoundry/cloud_controller_ng#1123]
## Issue

Cloud controller had trouble connecting to MySQL during a database migration. The subsequent retries then failed due to some of the tables already existing.

## Context

Our clean CF install with capi-release 1.44 failed its CC pre-start script due to a MySQL hiccup. The retries then failed due to some of the tables already having been created during the first failure.

## Steps to Reproduce

Not sure exactly, but maybe artificially shut down or disconnect the mysql instance during a database migration run by the cloud_controller_ng pre-start script.

## Expected result

The first migration should partially succeed and create some of the tables. The subsequent 2 retries should not recreate tables that already exist, and the reties should succeed.

## Current result

The current retries fail due to the following error:
```
...
[2018-04-06 16:34:13+0000] + perform_migration
[2018-04-06 16:34:13+0000] + pushd /var/vcap/packages/cloud_controller_ng/cloud_controller_ng
[2018-04-06 16:34:13+0000] + chpst -u vcap:vcap /var/vcap/jobs/cloud_controller_ng/bin/migrate_db
[2018-04-06 16:34:13+0000] + CC_PACKAGE_DIR=/var/vcap/packages/cloud_controller_ng
[2018-04-06 16:34:13+0000] + export BUNDLE_GEMFILE=/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/Gemfile
[2018-04-06 16:34:13+0000] + BUNDLE_GEMFILE=/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/Gemfile
[2018-04-06 16:34:13+0000] + main
[2018-04-06 16:34:13+0000] + migrate
[2018-04-06 16:34:13+0000] + set +e
[2018-04-06 16:34:13+0000] + echo 'Running migrations'
[2018-04-06 16:34:13+0000] + local result=1
[2018-04-06 16:34:13+0000] + local counter=1
[2018-04-06 16:34:13+0000] + local num_retries=3
[2018-04-06 16:34:13+0000] + [[ 1 -le 3 ]]
[2018-04-06 16:34:13+0000] + echo 'Running migration try number 1 of 3'
[2018-04-06 16:34:13+0000] + bundle exec rake db:migrate
[2018-04-06 16:34:13+0000] `/root` is not writable.
[2018-04-06 16:34:13+0000] Bundler will use `/tmp/bundler/home/bosh_26c32b6b21dc404' as your home directory temporarily.
[2018-04-06 16:34:16+0000] {"timestamp":1523032456.8495138,"message":"Begin applying migration 20130131184954_new_initial_schema.rb, direction: up","log_level":"info","source":"cc.db.migrations","data":{},"thread_id":47253497171800,"fiber_id":47253533616580,"process_id":12418,"file":"/var/vcap/packages/cloud_contro
ller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/logging.rb","lineno":88,"method":"block in log_each"}
[2018-04-06 16:34:16+0000] {"timestamp":1523032456.8558867,"message":"Mysql2::Error: Table 'billing_events' already exists: CREATE TABLE `billing_events` (`id` integer PRIMARY KEY AUTO_INCREMENT, `guid` varchar(255) NOT NULL, `created_at` Timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` Timestamp, `timest
amp` datetime NOT NULL, `kind` varchar(255) NOT NULL, `organization_guid` varchar(255) NOT NULL, `organization_name` varchar(255) NOT NULL, `space_guid` varchar(255), `space_name` varchar(255), `app_guid` varchar(255), `app_name` varchar(255), `app_plan_name` varchar(255), `app_run_id` varchar(255), `app_memory` in
teger, `app_instance_count` integer, `service_instance_guid` varchar(255), `service_instance_name` varchar(255), `service_guid` varchar(255), `service_label` varchar(255), `service_provider` varchar(255), `service_version` varchar(255), `service_plan_guid` varchar(255), `service_plan_name` varchar(255)) DEFAULT COL
LATE=utf8_bin","log_level":"error","source":"cc.db.migrations","data":{},"thread_id":47253497171800,"fiber_id":47253533616580,"process_id":12418,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/logging.rb","lineno":88,"method":"block
in log_each"}
[2018-04-06 16:34:16+0000] rake aborted!
[2018-04-06 16:34:16+0000] Sequel::DatabaseError: Mysql2::Error: Table 'billing_events' already exists
[2018-04-06 16:34:16+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.8/lib/mysql2/client.rb:120:in `_query'
[2018-04-06 16:34:16+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.8/lib/mysql2/client.rb:120:in `block in query'
[2018-04-06 16:34:16+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.8/lib/mysql2/client.rb:119:in `handle_interrupt'
[2018-04-06 16:34:16+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.8/lib/mysql2/client.rb:119:in `query'
[2018-04-06 16:34:16+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/mysql2.rb:141:in `block in _execute'
[2018-04-06 16:34:16+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/logging.rb:49:in `log_connection_yield'
[2018-04-06 16:34:16+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/mysql2.rb:136:in `_execute'
[2018-04-06 16:34:16+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/utils/mysql_mysql2.rb:37:in `block in execute'
[2018-04-06 16:34:16+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `block in synchronize'
[2018-04-06 16:34:16+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
[2018-04-06 16:34:16+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `synchronize'
[2018-04-06 16:34:16+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/utils/mysql_mysql2.rb:37:in `execute'
[2018-04-06 16:34:16+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/mysql2.rb:71:in `execute_dui'
[2018-04-06 16:34:16+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/query.rb:47:in `execute_ddl'
[2018-04-06 16:34:16+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/schema_methods.rb:697:in `create_table_from_generator'
[2018-04-06 16:34:16+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/schema_methods.rb:213:in `create_table'
[2018-04-06 16:34:16+0000] /var/vcap/data/packages/cloud_controller_ng/ecc5b5c2e755c52b9e3c548d34e49edb6549a0ec/cloud_controller_ng/db/migrations/20130131184954_new_initial_schema.rb:31:in `block (2 levels) in <top (required)>'
[2018-04-06 16:34:16+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:106:in `instance_eval'
[2018-04-06 16:34:16+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:106:in `apply'
[2018-04-06 16:34:16+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:705:in `block (2 levels) in run'
[2018-04-06 16:34:16+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:479:in `checked_transaction'
[2018-04-06 16:34:16+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:704:in `block in run'
[2018-04-06 16:34:16+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:701:in `each'
[2018-04-06 16:34:16+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:701:in `run'
[2018-04-06 16:34:16+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:404:in `run'
[2018-04-06 16:34:16+0000] /var/vcap/data/packages/cloud_controller_ng/ecc5b5c2e755c52b9e3c548d34e49edb6549a0ec/cloud_controller_ng/lib/cloud_controller/db_migrator.rb:18:in `apply_migrations'
[2018-04-06 16:34:16+0000] /var/vcap/data/packages/cloud_controller_ng/ecc5b5c2e755c52b9e3c548d34e49edb6549a0ec/cloud_controller_ng/lib/tasks/db.rake:50:in `migrate'
[2018-04-06 16:34:16+0000] /var/vcap/data/packages/cloud_controller_ng/ecc5b5c2e755c52b9e3c548d34e49edb6549a0ec/cloud_controller_ng/lib/tasks/db.rake:57:in `block (2 levels) in <top (required)>'
[2018-04-06 16:34:16+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
[2018-04-06 16:34:16+0000] /var/vcap/packages/ruby-2.4/bin/bundle:23:in `load'
[2018-04-06 16:34:16+0000] /var/vcap/packages/ruby-2.4/bin/bundle:23:in `<main>'
...
[2018-04-06 16:34:30+0000] Running migration try number 3 of 3
...
[2018-04-06 16:34:39+0000] + echo 'Migrations failed'
[2018-04-06 16:34:39+0000] + exit 1
```

## Possible Fix

We manually changed the migrations to use `create_table?` instead of `create_table`, to skip tables that already existed, and were able to successfully run the pre-start script manually on the VM.

cc: @heycait

**Comment by alexjh** [comment]
Hi @michelleheh,

we've seen this happen too - killing the switchboard process is fairly reliable at triggering this.

I've experimented with using transactions on the migrations and this seems to fix the problem.

```
--- db_migrator.rb  2018-08-31 20:51:17.964000000 +0000
+++ db_migrator.rb  2018-08-31 20:42:48.832000000 +0000
@@ -15,7 +15,7 @@
   def apply_migrations(opts={})
     Sequel.extension :migration
     require 'vcap/sequel_case_insensitive_string_monkeypatch'
-    Sequel::Migrator.run(@db, SEQUEL_MIGRATIONS, opts)
+    Sequel::Migrator.run(@db, SEQUEL_MIGRATIONS, opts.merge({:use_transactions=>true}))
   end

   def rollback(number_to_rollback)
```

However, this needs the sequel 5.x gem to handle it because of https://github.com/jeremyevans/sequel/issues/1407. However, various components fail because of this big version bump, so it's not an easy fix.

https://www.pivotaltracker.com/story/show/157068775 has been filed for the v5 upgrade.

**Comment by aashah** [comment]
There's some level of work that has been done in this space during https://github.com/cloudfoundry/capi-release/issues/165 that I think this issue has been resolved.
