### ISSUE TITLE
postgres detects deadlock during DB migration in pre_start

### ISSUE THREAD

**Issue by paolostivanin** [cloudfoundry/cloud_controller_ng#1133]
## Issue

we were upgrading from cf-deployment 1.21 to 1.27 (i.e.  from CAPI release 1.52 to 1.53)

Our productive CF landscape on AWS, the deployment failed repeatedly with errors:

```
Task 1589745 | 13:32:26 | Updating instance api: api/9715e088-cfc6-4811-8d40-6872c28da20d (0) (canary) (00:03:13)
                     L Error: Action Failed get_task: Task 3f480581-8477-4498-6200-dcbf0da0fdbe result: 1 of 6 pre-start scripts failed. Failed Jobs: cloud_controller_ng. Successful Jobs: cc_uploader, file_server, route_registrar, consul_agent, syslog_forwarder.
```

In the logs of the cloud_controller on api/9715e088-cfc6-4811-8d40-6872c28da20d we see a deadlock problem in the postgres:

```
[2018-05-02 14:20:08+0000] PG::TRDeadlockDetected: ERROR:  deadlock detected
[2018-05-02 14:20:08+0000] DETAIL:  Process 8669 waits for AccessExclusiveLock on relation 17509 of database 16389; blocked by process 56789.
[2018-05-02 14:20:08+0000] Process 56789 waits for AccessShareLock on relation 17412 of database 16389; blocked by process 8669.
[2018-05-02 14:20:08+0000] HINT:  See server log for query details.
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:166:in `async_exec'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:166:in `block in execute_query'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/logging.rb:49:in `log_connection_yield'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:166:in `execute_query'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:153:in `block in execute'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:129:in `check_disconnect_errors'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:153:in `execute'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:515:in `_execute'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:327:in `block (2 levels) in execute'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:537:in `check_database_errors'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:327:in `block in execute'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `block in synchronize'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/connection_pool/threaded.rb:103:in `hold'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `synchronize'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:327:in `execute'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/query.rb:54:in `execute_dui'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/query.rb:47:in `execute_ddl'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/schema_methods.rb:436:in `block in apply_alter_table'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/schema_methods.rb:436:in `each'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/schema_methods.rb:436:in `apply_alter_table'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/schema_methods.rb:449:in `apply_alter_table_generator'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/schema_methods.rb:94:in `alter_table'
[2018-05-02 14:20:08+0000] /var/vcap/data/packages/cloud_controller_ng/f93ea6e4f62a4c66f8d2ae06f245eb9d0e0e5900/cloud_controller_ng/db/migrations/20180220224558_add_missing_primary_keys.rb:27:in `block (2 levels) in <top (required)>'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:106:in `instance_eval'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:106:in `apply'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:705:in `block (2 levels) in run'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:224:in `_transaction'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:199:in `block in transaction'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `block in synchronize'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `synchronize'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:165:in `transaction'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:477:in `checked_transaction'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:704:in `block in run'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:701:in `each'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:701:in `run'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:404:in `run'
[2018-05-02 14:20:08+0000] /var/vcap/data/packages/cloud_controller_ng/f93ea6e4f62a4c66f8d2ae06f245eb9d0e0e5900/cloud_controller_ng/lib/cloud_controller/db_migrator.rb:18:in `apply_migrations'
[2018-05-02 14:20:08+0000] /var/vcap/data/packages/cloud_controller_ng/f93ea6e4f62a4c66f8d2ae06f245eb9d0e0e5900/cloud_controller_ng/lib/tasks/db.rake:50:in `migrate'
[2018-05-02 14:20:08+0000] /var/vcap/data/packages/cloud_controller_ng/f93ea6e4f62a4c66f8d2ae06f245eb9d0e0e5900/cloud_controller_ng/lib/tasks/db.rake:57:in `block (2 levels) in <top (required)>'
[2018-05-02 14:20:08+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
[2018-05-02 14:20:08+0000] /var/vcap/packages/ruby-2.4/bin/bundle:23:in `load'
[2018-05-02 14:20:08+0000] /var/vcap/packages/ruby-2.4/bin/bundle:23:in `<main>'
```

## Steps to Reproduce

the problem only happened on our productive CF instance. We are using RDS as CCDB (on a m4.4xlarge VM)

## Expected result

deploy should succeed without having to retry

## Current result

after retrying about ten times, the migration eventually succeeded. We suspect that the probability of deadlock is dependent on the general load created by CF API calls on the DB.

It looks like the migration script

https://github.com/cloudfoundry/cloud_controller_ng/commit/bd3a66e65669973671c034b430cd17e1c34d8267

introduced with CAPI 1.53 is prone to DB deadlocks.

**Comment by ericpromislow** [comment]
Hi @paolostivanin We addressed this issue in https://github.com/cloudfoundry/cloud_controller_ng/commit/00321c70a8fca52a9a5e393f0c30d12b25d35a8a 

It turns out the migration was flawed: Each table modification should be in a separate migration, and should also be reversible. We replaced that migration with ten individual ones which each check to see if the primary key exists before proceeding. In your case, these migrations should be no-ops going forward since your tables already have the new primary keys.  In the unlikely event you need to run `rake db:rollback`, the keys should be removed.  The flawed migration has been replaced with a no-op, as we can't delete migrations once they've been released.

<phew>. Sorry you ran into this issue, but thanks for reporting it.
