### ISSUE TITLE
pre-start script is failing on dbmigrate

### ISSUE THREAD

**Issue by lerytke** [cloudfoundry/cloud_controller_ng#1135]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

We are upgrading from capi  1.21.34 to capi 1.44.29  and when the pre-start script runs we get and error out a table already exisiting 

## Context

[2018-05-04 01:21:35+0000] Tasks: TOP => db:migrate
[2018-05-04 01:21:35+0000] (See full trace by running task with --trace)
[2018-05-04 01:21:35+0000] + result=1
[2018-05-04 01:21:35+0000] + [[ 1 -eq 0 ]]
[2018-05-04 01:21:35+0000] + sleep 5
[2018-05-04 01:21:40+0000] + (( counter++ ))
[2018-05-04 01:21:40+0000] + [[ 3 -le 3 ]]
[2018-05-04 01:21:40+0000] + echo 'Running migration try number 3 of 3'
[2018-05-04 01:21:40+0000] + bundle exec rake db:migrate
[2018-05-04 01:21:43+0000] rake aborted!
[2018-05-04 01:21:43+0000] Sequel::DatabaseError: Mysql2::Error: Table 'staging_security_groups_spaces' already exists
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.8/lib/mysql2/client.rb:120:in `_query'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.8/lib/mysql2/client.rb:120:in `block in query'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.8/lib/mysql2/client.rb:119:in `handle_interrupt'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.8/lib/mysql2/client.rb:119:in `query'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/mysql2.rb:141:in `block in _execute'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/logging.rb:49:in `log_connection_yield'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/mysql2.rb:136:in `_execute'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/utils/mysql_mysql2.rb:37:in `block in execute'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `block in synchronize'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `synchronize'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/utils/mysql_mysql2.rb:37:in `execute'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/mysql2.rb:71:in `execute_dui'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/query.rb:47:in `execute_ddl'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/schema_methods.rb:697:in `create_table_from_generator'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/schema_methods.rb:213:in `create_table'
[2018-05-04 01:21:43+0000] /var/vcap/data/packages/cloud_controller_ng/ecc5b5c2e755c52b9e3c548d34e49edb6549a0ec/cloud_controller_ng/db/migrations/20161104184720_create_staging_security_groups_spaces.rb:3:in `block (2 levels) in <top (required)>'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:106:in `instance_eval'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:106:in `apply'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:705:in `block (2 levels) in run'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:479:in `checked_transaction'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:704:in `block in run'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:701:in `each'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:701:in `run'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:404:in `run'
[2018-05-04 01:21:43+0000] /var/vcap/data/packages/cloud_controller_ng/ecc5b5c2e755c52b9e3c548d34e49edb6549a0ec/cloud_controller_ng/lib/cloud_controller/db_migrator.rb:18:in `apply_migrations'
[2018-05-04 01:21:43+0000] /var/vcap/data/packages/cloud_controller_ng/ecc5b5c2e755c52b9e3c548d34e49edb6549a0ec/cloud_controller_ng/lib/tasks/db.rake:50:in `migrate'
[2018-05-04 01:21:43+0000] /var/vcap/data/packages/cloud_controller_ng/ecc5b5c2e755c52b9e3c548d34e49edb6549a0ec/cloud_controller_ng/lib/tasks/db.rake:57:in `block (2 levels) in <top (required)>'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
[2018-05-04 01:21:43+0000] /var/vcap/packages/ruby-2.4/bin/bundle:23:in `load'
[2018-05-04 01:21:43+0000] /var/vcap/packages/ruby-2.4/bin/bundle:23:in `<main>'
[2018-05-04 01:21:43+0000] Mysql2::Error: Table 'staging_security_groups_spaces' already exists
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.8/lib/mysql2/client.rb:120:in `_query'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.8/lib/mysql2/client.rb:120:in `block in query'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.8/lib/mysql2/client.rb:119:in `handle_interrupt'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.8/lib/mysql2/client.rb:119:in `query'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/mysql2.rb:141:in `block in _execute'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/logging.rb:49:in `log_connection_yield'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/mysql2.rb:136:in `_execute'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/utils/mysql_mysql2.rb:37:in `block in execute'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `block in synchronize'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `synchronize'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/utils/mysql_mysql2.rb:37:in `execute'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/mysql2.rb:71:in `execute_dui'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/query.rb:47:in `execute_ddl'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/schema_methods.rb:697:in `create_table_from_generator'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/schema_methods.rb:213:in `create_table'
[2018-05-04 01:21:43+0000] /var/vcap/data/packages/cloud_controller_ng/ecc5b5c2e755c52b9e3c548d34e49edb6549a0ec/cloud_controller_ng/db/migrations/20161104184720_create_staging_security_groups_spaces.rb:3:in `block (2 levels) in <top (required)>'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:106:in `instance_eval'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:106:in `apply'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:705:in `block (2 levels) in run'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:479:in `checked_transaction'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:704:in `block in run'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:701:in `each'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:701:in `run'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:404:in `run'
[2018-05-04 01:21:43+0000] /var/vcap/data/packages/cloud_controller_ng/ecc5b5c2e755c52b9e3c548d34e49edb6549a0ec/cloud_controller_ng/lib/cloud_controller/db_migrator.rb:18:in `apply_migrations'
[2018-05-04 01:21:43+0000] /var/vcap/data/packages/cloud_controller_ng/ecc5b5c2e755c52b9e3c548d34e49edb6549a0ec/cloud_controller_ng/lib/tasks/db.rake:50:in `migrate'
[2018-05-04 01:21:43+0000] /var/vcap/data/packages/cloud_controller_ng/ecc5b5c2e755c52b9e3c548d34e49edb6549a0ec/cloud_controller_ng/lib/tasks/db.rake:57:in `block (2 levels) in <top (required)>'
[2018-05-04 01:21:43+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
[2018-05-04 01:21:43+0000] /var/vcap/packages/ruby-2.4/bin/bundle:23:in `load'
[2018-05-04 01:21:43+0000] /var/vcap/packages/ruby-2.4/bin/bundle:23:in `<main>'

## Steps to Reproduce

we are using Pivotal bits so we are doing and upgrade from 1.10.22 to 2.0.10, this databse was first deployed using 1.7?

## Expected result

db migration to work successfully 

## Current result

the cloud_controller_ng pre-start script is failing

**Comment by infews** [comment]
@lerytke have you contacted Pivotal support?

@bingosummer Is your issue resolved?

Thanks,
@selzoc && Davis

**Comment by bingosummer** [comment]
@infews Thanks for asking. We just upgraded to new version. Currently, we use v4.0.0 and didn't hit the issue.

**Comment by selzoc** [comment]
Thank you for following up, @bingosummer !

**Comment by selzoc** [comment]
@lerytke we haven't heard from you in over 2 weeks, closing this issue for now.   Please feel free to re-open if you're still having the issue.

Thanks,
Chris
