### ISSUE TITLE
GET /v2/routes?q=organization_guid:<> returns 500 (Database error)

### ISSUE THREAD

**Issue by stephanme** [cloudfoundry/cloud_controller_ng#1149]
## Issue

GET /v2/routes?q=organization_guid:<> returns 500 under certain circumstances. Underlying error is a bad SQL statement (PG::AmbiguousColumn).

We observe around 60% 200 and 40% 500 responses on a test landscape.

## Context

cf-deployment 1.36.0
capi-release 1.58.0

## Steps to Reproduce

cf curl '/v2/routes?q=organization_guid:a80e5ea1-fdf5-4d58-9131-3f311af57300&results-per-page=100'

Not yet clear how to reproduce as not all calls fail.

## Expected result

Route list and status code 200.

## Current result

Status code 500

{
   "description": "Database error",
   "error_code": "CF-DatabaseError",
   "code": 10011
}

```
{"timestamp":1527597735.2560728,"message":"exception not translated: Sequel::DatabaseError - PG::AmbiguousColumn: ERROR:  column reference "guid" is ambiguous
LINE 1: ...tions"."id" = "spaces"."organization_id") WHERE (("guid" IN ...
                                                             ^:
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:166:in `async_exec'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:166:in `block in execute_query'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/logging.rb:49:in `log_connection_yield'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:166:in `execute_query'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:153:in `block in execute'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:129:in `check_disconnect_errors'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:153:in `execute'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:515:in `_execute'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:327:in `block (2 levels) in execute'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:537:in `check_database_errors'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:327:in `block in execute'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `block in synchronize'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `synchronize'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:327:in `execute'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/dataset/actions.rb:1135:in `execute'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:680:in `fetch_rows'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/dataset/actions.rb:989:in `with_sql_each'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/dataset/actions.rb:997:in `with_sql_first'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/dataset/actions.rb:1005:in `with_sql_single_value'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/dataset/actions.rb:774:in `single_value!'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/dataset/actions.rb:111:in `count'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/pagination.rb:43:in `paginate'
/var/vcap/data/packages/cloud_controller_ng/f71341cbdef726697d29f761a8b46863485b28ff/cloud_controller_ng/lib/cloud_controller/rest_controller/paginated_collection_renderer.rb:57:in `render_json'
/var/vcap/data/packages/cloud_controller_ng/f71341cbdef726697d29f761a8b46863485b28ff/cloud_controller_ng/app/controllers/base/model_controller.rb:101:in `enumerate'
/var/vcap/data/packages/cloud_controller_ng/f71341cbdef726697d29f761a8b46863485b28ff/cloud_controller_ng/app/controllers/base/base_controller.rb:86:in `dispatch'
/var/vcap/data/packages/cloud_controller_ng/f71341cbdef726697d29f761a8b46863485b28ff/cloud_controller_ng/lib/cloud_controller/rest_controller/routes.rb:16:in `block in define_route'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1610:in `call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1610:in `block in compile!'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.5/lib/rack/protection/xss_header.rb:18:in `call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.5/lib/rack/protection/path_traversal.rb:16:in `call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.5/lib/rack/protection/json_csrf.rb:18:in `call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.5/lib/rack/protection/frame_options.rb:31:in `call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-1.6.9/lib/rack/nulllogger.rb:9:in `call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-1.6.9/lib/rack/head.rb:13:in `call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-1.6.9/lib/rack/urlmap.rb:66:in `block in call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-1.6.9/lib/rack/urlmap.rb:50:in `each'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-1.6.9/lib/rack/urlmap.rb:50:in `call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/rate_limiter.rb:43:in `call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/request_logs.rb:22:in `call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/security_context_setter.rb:19:in `call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/vcap_request_id.rb:15:in `call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/cors.rb:49:in `call_app'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/cors.rb:14:in `call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/middleware/request_metrics.rb:12:in `call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-1.6.9/lib/rack/builder.rb:153:in `call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/thin/connection.rb:86:in `block in pre_process'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `catch'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `pre_process'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/thin-1.7.0/lib/thin/connection.rb:50:in `block in process'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:1067:in `block in spawn_threadpool'","log_level":"warn","source":"cc.api","data":{"request_guid":"ed7461eb-ae01-4042-62d8-2ca3b84ff061::14a5fbb0-7408-419a-a6b4-64a438369242"},"thread_id":47413879359660,"fiber_id":47413879488080,"process_id":22161,"file":"/var/vcap/data/packages/cloud_controller_ng/f71341cbdef726697d29f761a8b46863485b28ff/cloud_controller_ng/app/controllers/base/base_controller.rb","lineno":317,"method":"translate_and_log_exception"}
```

SQL query was: 
```
SELECT count(*) AS "count" FROM "routes" LEFT JOIN "spaces" ON ("spaces"."id" = "routes"."space_id") LEFT JOIN "organizations" ON ("organizations"."id" = "spaces"."organization_id") WHERE (("guid" IN ('d6c987b5-13cd-4562-88d5-856531e1700b')) AND ("organizations"."guid" IN ('a80e5ea1-fdf5-4d58-9131-3f311af57300'))) LIMIT 1
```

`"guid" IN ('d6c987b5-13cd-4562-88d5-856531e1700b')` seems to stand for route list.

If the same call succeeds (which happens but it is unclear if the content of the org has changed meanwhile), it returns:

```
$ cf curl '/v2/routes?q=organization_guid:a80e5ea1-fdf5-4d58-9131-3f311af57300&results-per-page=100'
{
   "total_results": 1,
   "total_pages": 1,
   "prev_url": null,
   "next_url": null,
   "resources": [
      {
         "metadata": {
            "guid": "d6c987b5-13cd-4562-88d5-856531e1700b",
            "url": "/v2/routes/d6c987b5-13cd-4562-88d5-856531e1700b",
            "created_at": "2018-05-27T07:57:11Z",
            "updated_at": "2018-05-27T07:57:11Z"
         },
         "entity": {
            "host": "myapplicationaa",
            "path": "",
            "domain_guid": "30b8fd61-2327-4f15-9940-2274f1760db4",
            "space_guid": "bbd79ecf-ab92-4ca8-a6ed-0645db87782a",
            "service_instance_guid": null,
            "port": null,
            "domain_url": "/v2/shared_domains/30b8fd61-2327-4f15-9940-2274f1760db4",
            "space_url": "/v2/spaces/bbd79ecf-ab92-4ca8-a6ed-0645db87782a",
            "apps_url": "/v2/routes/d6c987b5-13cd-4562-88d5-856531e1700b/apps",
            "route_mappings_url": "/v2/routes/d6c987b5-13cd-4562-88d5-856531e1700b/route_mappings"
         }
      }
   ]
}
```

## Possible Fix

n/a

**Comment by stephanme** [comment]
https://github.com/cloudfoundry/cloud_controller_ng/commit/5984648e58c2e7b346460803f9abe7ba328a6e1c fixed this bug.

We worked around it by cherry-picking this commit, building a capi-release 1.58.1 patch release and consuming this via ops file on top of cf-deployment 1.36.0.

I wonder why nobody else detected this problem. Maybe cf cli doesn't use this CC api call or only in rare use cases.

**Comment by stephanme** [comment]
Fix is included in https://github.com/cloudfoundry/capi-release/releases/tag/1.59.0 = https://github.com/cloudfoundry/cloud_controller_ng/commits/6e070d7f7faccd3b997249212b4d22e45ab204fb

(and then in https://github.com/cloudfoundry/cf-deployment/releases/tag/v1.38.0)

**Comment by zrob** [comment]
glad this is fixed for you.

we had it tracked via this bug as well https://www.pivotaltracker.com/story/show/157822597
