### ISSUE TITLE
Deleting a user with space permissions within an organisation fails

### ISSUE THREAD

**Issue by LeePorte** [cloudfoundry/cloud_controller_ng#1160]
## Issue

When trying to delete a user from an organisation, if they have any permissions within the organisation it fails.

## Context

We have created an admin interface on top of the cf API in order to enable our users to undertake some self administration. One of the requests we have had is to be able to remove users from organisations.

It is possible that one user may work across multiple organisations, thus not being deleted in entirety from our CF installation is desirable. We have taken the approach to implement calling  `cf: delete /v2/organizations/<org GUID>/users/<user GUID>` to achieve this.

However we have encountered an issue with this approach

## Steps to Reproduce

1. Create a new user
1. Assign permissions within an organisation
1. Attempt to delete the user with `cf: delete /v2/organizations/<org GUID>/users/<user GUID>`

## Expected result

I would expect that the user and all permissions were successfully removed.

## Current result

Currently this process generates an error due to `CF-AssociationNotEmpty`

This requires us to remove all permissions for the user before being able to delete them. In an organisation with a large number of spaces this can be quite time consuming.

Logs 

```
2018-06-11T10:52:52.73+0100 [RTR/0] OUT admin.leeporte.dev.cloudpipeline.digital - [2018-06-11T09:52:52.730+0000] "GET /assets/kv5bawckhqvxpsd72eapuw2pp.open-government-licence.png HTTP/1.1" 304 0 0 "https://admin.leeporte.dev.cloudpipeline.digital/assets/5jndywfdmtmpav7tqxsc2vt3tc.govuk-template.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36" "127.0.0.1:10368" "10.0.33.4:61126" x_forwarded_for:"213.86.153.212, 127.0.0.1" x_forwarded_proto:"https" vcap_request_id:"22ad5381-2e5f-4c58-47c8-94a291ed41a7" response_time:0.002648015 app_id:"7e8facb6-38f4-4c63-9310-f0912720fe9b" app_index:"1" x_b3_traceid:"184b7a97d620e9a6" x_b3_spanid:"184b7a97d620e9a6" x_b3_parentspanid:"-"
   2018-06-11T10:52:52.73+0100 [RTR/0] OUT 
   2018-06-11T10:52:55.05+0100 [APP/PROC/WEB/1] OUT {"level":50,"time":1528710774919,"msg":"cf: delete /v2/organizations/356bb6e8-2cd4-4b10-bca3-d044637a34cf/users/10bb85ee-e83c-4c6a-bf8a-d7cc4f6a3b4e failed with status 400 and data {\"description\":\"Please delete the user associations for your spaces in the org.\",\"error_code\":\"CF-AssociationNotEmpty\",\"code\":10006}","pid":10,"hostname":"ea378111-5b0f-44db-59f6-eb1e","req":{"method":"POST","url":"/organisations/356bb6e8-2cd4-4b10-bca3-d044637a34cf/users/10bb85ee-e83c-4c6a-bf8a-d7cc4f6a3b4e/delete"},"type":"Error","stack":"Error: cf: delete /v2/organizations/356bb6e8-2cd4-4b10-bca3-d044637a34cf/users/10bb85ee-e83c-4c6a-bf8a-d7cc4f6a3b4e failed with status 400 and data {\"description\":\"Please delete the user associations for your spaces in the org.\",\"error_code\":\"CF-AssociationNotEmpty\",\"code\":10006}\n    at /home/vcap/app/dist/webpack:/src/cf/cf.ts:246:17\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/vcap/app/node_modules/tslib/tslib.js:104:62)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)","v":1}
``` 

## Possible Fix

The ideal behaviour would be that when `cf: delete /v2/organizations/<org GUID>/users/<user GUID>` is called all permissions for that user would be deleted within the organisation and finally removing the user.

**Comment by paroxp** [comment]
As per documentation:

https://apidocs.cloudfoundry.org/1.40.0/organizations/remove_user_from_the_organization.html

The `recursive` query parameter can be provided into the call, achieving the desired outcome. The question is, could/should the default change?

./cc @LeePorte

**Comment by zrob** [comment]
@LeePorte were you able to resolve your issue using the suggested `recursive` query parameter?

**Comment by paroxp** [comment]
Yeah, we have. It's cool to close the issue.
