### ISSUE TITLE
Request Outstanding metric is not decremented if the DB connection is broken while processing a HTTP request

### ISSUE THREAD

**Issue by chombium** [cloudfoundry/cloud_controller_ng#1294]
Hello,

we have found an issue with the "request outstanding" metric if the db connection is lost while processing a HTTP request.

## Issue

Request Outstanding metric is not decremented if the DB connection is broken during processing of a HTTP request.

## Context

In our cloud controller health monitoring among the other metrics we are observing "request outstanding". Some time ago we have noticed that this metric on the cloud controller's api nodes got a high value and kept this as a constant. After this all the new values were oscillating around this value. The only way to get it back to normal is to restart the cloud controller. We have analyzed our logs and the logs of our IaaS provider and we have noticed that the database connection was broken, possibly due to a network issue. The cloud controller has recovered from the database connection problem, but the number of the outstanding request stayed high.

For the sent HTTP request during the db connection problem, the response status was 500, but the value of the outstanding request was not decremented.

## Steps to Reproduce

We have tried to run the unit tests, but we've found it a bit hard to simulate a DB connection failure.
The unit tests are using a real PostgreSQL database, so our basic idea was to try to run a unit test and kill the db server while the test is running.
With a watch clock, knowing the test's file loading time and a bit of practice, we were able to simulate the db connection problem :)

At first we tested with the internal update package tests [internal_package_update_spec.rb](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/spec/unit/actions/internal_package_update_spec.rb#L28) test and [package_update_spec.rb](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/spec/unit/actions/package_update_spec.rb) so that we are sure that we can simulate the problem.

Here is how we run the first test and the results of it's execution:

```
# DB_CONNECTION_STRING="postgres://postgres:postgres@localhost:5432/cc_test" DB=postgres bundle exec rspec spec/unit/actions/internal_package_update_spec.rb:28
FATAL:  terminating connection due to administrator command

An error occurred while loading ./spec/unit/actions/internal_package_update_spec.rb.
Failure/Error: Sequel::Migrator.run(@db, SEQUEL_MIGRATIONS, opts)

Sequel::DatabaseDisconnectError:
  PG::ConnectionBad: PQconsumeInput() SSL connection has been closed unexpectedly
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:152:in `async_exec'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:152:in `block in execute_query'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/database/logging.rb:38:in `log_connection_yield'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:152:in `execute_query'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:140:in `block in execute'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:116:in `check_disconnect_errors'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:140:in `execute'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:597:in `log_connection_execute'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/database/transactions.rb:377:in `commit_transaction'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/adapters/shared/postgres.rb:858:in `commit_transaction'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/database/transactions.rb:362:in `commit_or_rollback_transaction'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/database/transactions.rb:257:in `_transaction'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/database/transactions.rb:220:in `block in transaction'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/connection_pool/threaded.rb:88:in `hold'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/database/connecting.rb:270:in `synchronize'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/database/transactions.rb:186:in `transaction'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/database/schema_methods.rb:696:in `block in create_table_indexes_from_generator'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/database/schema_methods.rb:693:in `each'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/database/schema_methods.rb:693:in `create_table_indexes_from_generator'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/database/schema_methods.rb:195:in `create_table'
# ./db/migrations/20190128233032_create_buildpack_metadata_tables.rb:3:in `block (2 levels) in <top (required)>'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/extensions/migration.rb:107:in `instance_exec'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/extensions/migration.rb:107:in `apply'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/extensions/migration.rb:684:in `block (2 levels) in run'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/database/transactions.rb:245:in `_transaction'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/database/transactions.rb:220:in `block in transaction'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/database/connecting.rb:270:in `synchronize'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/database/transactions.rb:186:in `transaction'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/extensions/migration.rb:475:in `checked_transaction'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/extensions/migration.rb:683:in `block in run'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/extensions/migration.rb:680:in `each'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/extensions/migration.rb:680:in `run'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/extensions/migration.rb:402:in `run'
# ./lib/cloud_controller/db_migrator.rb:18:in `apply_migrations'
# ./spec/support/bootstrap/table_recreator.rb:21:in `recreate_tables'
# ./spec/support/bootstrap/spec_bootstrap.rb:24:in `init'
# ./spec/spec_helper.rb:85:in `block in <top (required)>'
# ./spec/spec_helper.rb:203:in `<top (required)>'
# ./spec/unit/actions/internal_package_update_spec.rb:1:in `require'
# ./spec/unit/actions/internal_package_update_spec.rb:1:in `<top (required)>'
# ------------------
# --- Caused by: ---
# PG::ConnectionBad:
#   PQconsumeInput() SSL connection has been closed unexpectedly
#   /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:152:in `async_exec'
Run options: include {:locations=>{"./spec/unit/actions/internal_package_update_spec.rb"=>[28]}}

All examples were filtered out

Randomized with seed 25395


Finished in 0.00096 seconds (files took 5.7 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

Randomized with seed 25395
```

The next step was to run an api request and brake the db connection.
We have tried to run the [packages_spec.rb](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/spec/request/packages_spec.rb#L902) `PATCH /internal/v4/packages/:guid` and we could get the database connection error, but we were not able to let the request finish and get the test failed with HTTP response code 500.

Here is a log from one of the tries:
```
# DB_CONNECTION_STRING="postgres://postgres:postgres@localhost:5432/cc_test" DB=postgres bundle exec rspec spec/request/packages_spec.rb:921

An error occurred while loading ./spec/request/packages_spec.rb.
Failure/Error:
  class TaskAnnotationModel < Sequel::Model(:task_annotations)
    many_to_one :task,
      class: 'VCAP::CloudController::TaskModel',
      primary_key: :guid,
      key: :resource_guid,
      without_guid_generation: true

Sequel::DatabaseConnectionError:
  PG::ConnectionBad: FATAL:  the database system is shutting down
  FATAL:  the database system is shutting down
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:206:in `initialize'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:206:in `new'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:206:in `connect'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/connection_pool.rb:127:in `make_new'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/connection_pool/threaded.rb:209:in `assign_connection'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/connection_pool/threaded.rb:139:in `acquire'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/extensions/connection_validator.rb:98:in `acquire'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/database/connecting.rb:270:in `synchronize'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/database/transactions.rb:186:in `transaction'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/model/base.rb:725:in `check_non_connection_error'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/model/base.rb:811:in `block in get_db_schema'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/model/base.rb:844:in `get_db_schema'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/model/base.rb:644:in `set_dataset'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/model/base.rb:192:in `Model'
# /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/model/base.rb:140:in `block in def_Model'
# ./app/models/runtime/task_annotation_model.rb:2:in `<module:CloudController>'
# ./app/models/runtime/task_annotation_model.rb:1:in `<top (required)>'
# /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
# /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
# /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
# /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
# ./app/models.rb:86:in `<top (required)>'
# /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
# /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
# /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
# /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
# ./lib/cloud_controller/db.rb:36:in `load_models'
# ./spec/support/bootstrap/spec_bootstrap.rb:26:in `init'
# ./spec/spec_helper.rb:85:in `block in <top (required)>'
# ./spec/spec_helper.rb:203:in `<top (required)>'
# ./spec/request/packages_spec.rb:1:in `require'
# ./spec/request/packages_spec.rb:1:in `<top (required)>'
# ------------------
# --- Caused by: ---
# PG::ConnectionBad:
#   FATAL:  the database system is shutting down
#   FATAL:  the database system is shutting down
#   /usr/local/bundle/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:206:in `initialize'
Run options: include {:locations=>{"./spec/request/packages_spec.rb"=>[921]}}

All examples were filtered out

Randomized with seed 6636


Finished in 0.00084 seconds (files took 6.38 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

Any idea or suggestion how to test this problem better is more than welcome :)

## Expected result

Despite the database connection problem, the HTTP requests are properly completed with response code 500 and the number of outstanding request is decremented after each request completion.

## Current result

The HTTP requests are completed with status 500, but the variable which hold the value of the outstanding requests is not decremented.

#### Relevant logs in order or appearance:
```
2019-02-01T07:57:58.533394Z x.y.z.q cloud_controller_ng rsX - [instance@XXXXX director="XXXXX" deployment="cf" group="api" az="z1" id="d60f66a0-a835-4765-83ab-7a4d43f97bc6"]
{
  "timestamp": 1549007878.0163171,
  "message": "Started PATCH \"/internal/v4/packages/2c21a88b-4220-4b61-88d2-f45050d8c7b5\" for user: , ip: 127.0.0.1 with vcap-request-id: ef89ade0-795b-4b98-bb50-c11968fc5190 at 2019-02-01 07:57:58 UTC",
  "log_level": "info",
  "source": "cc.api",
  "data": {
    "request_guid": "ef89ade0-795b-4b98-bb50-c11968fc5190"
  },
  "thread_id": 47312831559380,
  "fiber_id": 47312850700960,
  "process_id": 1,
  "file": "/var/vcap/data/packages/cloud_controller_ng/5c352b055de026f824dd17016264abeb1acc792a/cloud_controller_ng/middleware/request_logs.rb",
  "lineno": 12,
  "method": "call"
}

2019-02-01T07:57:58.533413Z x.y.z.q cloud_controller_ng rsX - [instance@XXXXX director="XXXXX" deployment="cf" group="api" az="z1" id="d60f66a0-a835-4765-83ab-7a4d43f97bc6"]
{
  "timestamp": 1549007878.021569,
  "message": "Updating package 2c21a88b-4220-4b61-88d2-f45050d8c7b5",
  "log_level": "info",
  "source": "cc.action.package_update",
  "data": {
    "request_guid": "ef89ade0-795b-4b98-bb50-c11968fc5190"
  },
  "thread_id": 47312831559380,
  "fiber_id": 47312850700960,
  "process_id": 1,
  "file": "/var/vcap/data/packages/cloud_controller_ng/5c352b055de026f824dd17016264abeb1acc792a/cloud_controller_ng/app/actions/package_update.rb",
  "lineno": 13,
  "method": "update"
}

2019-02-01T07:57:58.533405Z x.y.z.q cloud_controller_ng rs2 - [instance@XXXXX director="XXXXX" deployment="cf" group="api" az="z1" id="d60f66a0-a835-4765-83ab-7a4d43f97bc6"]
{
  "timestamp": 1549007878.0210505,
  "message": "(0.002946s) SELECT * FROM \"packages\" WHERE (\"guid\" = '2c21a88b-4220-4b61-88d2-f45050d8c7b5') LIMIT 1",
  "log_level": "info",
  "source": "cc.db",
  "data": {
    "request_guid": "ef89ade0-795b-4b98-bb50-c11968fc5190"
  },
  "thread_id": 47312831559380,
  "fiber_id": 47312850700960,
  "process_id": 1,
  "file": "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/logging.rb",
  "lineno": 88,
  "method": "block in log_each"
}

2019-02-01T07:57:58.533417Z x.y.z.q cloud_controller_ng rsX - [instance@XXXXX director="XXXXX" deployment="cf" group="api" az="z1" id="d60f66a0-a835-4765-83ab-7a4d43f97bc6"]
{
  "timestamp": 1549007878.043685,
  "message": "PG::ConnectionBad: PQconsumeInput() server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.: BEGIN",
  "log_level": "error",
  "source": "cc.db",
  "data": {
    "request_guid": "ef89ade0-795b-4b98-bb50-c11968fc5190"
  },
  "thread_id": 47312831559380,
  "fiber_id": 47312850700960,
  "process_id": 1,
  "file": "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/logging.rb",
  "lineno": 88,
  "method": "block in log_each"
}

2019-02-01T07:57:58.533437Z x.y.z.q cloud_controller_ng rsX - [instance@XXXXX director="XXXXX" deployment="cf" group="api" az="z1" id="d60f66a0-a835-4765-83ab-7a4d43f97bc6"]
{
  "timestamp": 1549007878.0526175,
  "message": "PG::ConnectionBad: PQsocket() can't get socket descriptor: ROLLBACK",
  "log_level": "error",
  "source": "cc.db",
  "data": {
    "request_guid": "ef89ade0-795b-4b98-bb50-c11968fc5190"
  },
  "thread_id": 47312831559380,
  "fiber_id": 47312850700960,
  "process_id": 1,
  "file": "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/logging.rb",
  "lineno": 88,
  "method": "block in log_each"
}

2019-02-01T07:57:58.533437Z x.y.z.q cloud_controller_ng rsX - [instance@XXXXX director="XXXXX" deployment="cf" group="api" az="z1" id="d60f66a0-a835-4765-83ab-7a4d43f97bc6"]
{
  "timestamp":1549007878.0562575,
  "message":"
  exception not translated: Sequel::<mark>DatabaseDisconnectError</mark> - PG::ConnectionBad: PQconsumeInput() server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
:
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:166:in `async_exec'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:166:in `block in execute_query'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/logging.rb:49:in `log_connection_yield'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:166:in `execute_query'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:153:in `block in execute'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:129:in `check_disconnect_errors'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:153:in `execute'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:628:in `log_connection_execute'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:310:in `begin_new_transaction'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/shared/postgres.rb:767:in `begin_new_transaction'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:320:in `begin_transaction'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:214:in `_transaction'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:199:in `block in transaction'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `block in synchronize'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `synchronize'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:165:in `transaction'
/var/vcap/data/packages/cloud_controller_ng/5c352b055de026f824dd17016264abeb1acc792a/cloud_controller_ng/app/actions/package_update.rb:15:in `update'
/var/vcap/data/packages/cloud_controller_ng/5c352b055de026f824dd17016264abeb1acc792a/cloud_controller_ng/app/controllers/internal/packages_controller.rb:18:in `update'
/var/vcap/data/packages/cloud_controller_ng/5c352b055de026f824dd17016264abeb1acc792a/cloud_controller_ng/app/controllers/base/base_controller.rb:86:in `dispatch'
/var/vcap/data/packages/cloud_controller_ng/5c352b055de026f824dd17016264abeb1acc792a/cloud_controller_ng/lib/cloud_controller/rest_controller/routes.rb:16:in `block in define_route'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1634:in `call'
"

2019-02-01T07:57:58.533458Z x.y.z.q cloud_controller_ng rsX - [instance@XXXXX director="XXXXX" deployment="cf" group="api" az="z1" id="d60f66a0-a835-4765-83ab-7a4d43f97bc6"]
{
  "timestamp": 1549007878.0579748,
  "message": "Completed 500 vcap-request-id: ef89ade0-795b-4b98-bb50-c11968fc5190",
  "log_level": "info",
  "source": "cc.api",
  "data": {
    "request_guid": "ef89ade0-795b-4b98-bb50-c11968fc5190"
  },
  "thread_id": 47312831559380,
  "fiber_id": 47312850700960,
  "process_id": 1,
  "file": "/var/vcap/data/packages/cloud_controller_ng/5c352b055de026f824dd17016264abeb1acc792a/cloud_controller_ng/middleware/request_logs.rb",
  "lineno": 24,
  "method": "call"
}
```

## Possible Fix

We have analyzed the source code and found that the value of the outstanding request metric is incremented and decremented only on one place in [request_metrics.rb](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/lib/cloud_controller/metrics/request_metrics.rb) and these functions are only called from [request_metrics.rb middleware](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/middleware/request_metrics.rb).

From what we've seen in the code, our assumption is that when the request metrics middleware is executed, the value for the outstanding request is incremented, in the further middleware chain execution is broken due to the database connection problem, the HTTP request is finished with status 500, but the execution never gets to the [@request_metrics.complete_request(status)](https://github.com/cloudfoundry/cloud_controller_ng/blob/90bbddabf983a353297a11aa8a2bcc1f98b81503/middleware/request_metrics.rb#L14) line in the middleware.

Can someone please take a look at this?
Any help is more than welcome.

Best Regards,
Jovan

**Comment by tcdowney** [comment]
Thank you for your very detailed summary of this issue @chombium! We'll take a look in to why it's not decrementing as it should.

**Comment by chombium** [comment]
Another idea how to reproduce this problem that crossed my mind right now is to add some code which will break the db connection after the unit test initialization is finished and let it run, but I don't know the code base...

**Comment by sethboyles** [comment]
I think this should have been fixed as part of https://github.com/cloudfoundry/cloud_controller_ng/issues/2393 and the corresponding PR: https://github.com/cloudfoundry/cloud_controller_ng/pull/2394
