### ISSUE TITLE
CC worker returns a 500 when it fails to find a blob it tries to delete via bits-service

### ISSUE THREAD

**Issue by jspawar** [cloudfoundry/cloud_controller_ng#1320]
## Issue

We have noticed there were some recurring failures in our CC workers when they tried to delete some blobs (we think they're packages or droplets?) via the bits-service. It looks like the bits-service is returning 404s for the particular object it is trying to delete and the worker reports that as an internal server error. 

## Context

We are using project Eirini to deploy apps and Diego to stage them using standard `cf-deployment` with bits-service added on/enabled. 

Unsure whether or not Eirini is somehow interfering here, but it seems unlikely since the only calls to the bits-service we know of that Eirini explicitly performs are to download a particular droplet from the blobstore through it. 

## Steps to Reproduce

1. Deploy an app
2. Delete an app

## Expected result

No internal server errors from the cc-worker. 

Seems like there might be some objects leftover in the blobstore as well that it should've deleted but didn't. Appears we have some droplets leftover that aren't being cleaned up on delete or otherwise, might be a separate issue.

## Current result

We are receiving internal server errors for some cc-worker jobs which eventually backoff from repeated failures. 

```
{"timestamp":1554761049.9775925,"message":"Request failed: 500: {\"error_code\"=>\"UnknownError\", \"description\"=>\"An unknown error occurred.\", \"code\"=>10001, \"test_mode_info\"=>{\"description\"=>\"Could not find object 'e0650ce1-2bdf-40e3-bacd-5 732c11e2e8a', 404/\", \"error_code\"=>\"CF-FileNotFound\", \"backtrace\"=>[\"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/bits_service_client-3.3.0/lib/bits_service_client/client.rb:99:in `delete'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/bits_service_client-3.3.0/lib/bits_service_client/client.rb:116:in `delete_blob'\", \"/var/vcap/data/packages/cloud_controller_ng /15a3557a65dd828af0f5ed52633be1f8c3a269e0/cloud_controller_ng/app/jobs/runtime/blobstore_delete.rb:21:in `perform'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/cloud_controller_ng/app/jobs/wrapping_job.rb:11: in `perform'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/cloud_controller_ng/app/jobs/timeout_job.rb:13:in `block in perform'\", \"/var/vcap/data/packages/ruby-2.4-r5/697e94aad1386999dbb4b0076540305ec07c129a /lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'\", \"/var/vcap/data/packages/ruby-2.4-r5/697e94aad1386999dbb4b0076540305ec07c129a/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'\", \"/var/vcap/data/packages/ruby-2.4-r5/697e94aad1386999dbb4b00765403 05ec07c129a/lib/ruby/2.4.0/timeout.rb:33:in `catch'\", \"/var/vcap/data/packages/ruby-2.4-r5/697e94aad1386999dbb4b0076540305ec07c129a/lib/ruby/2.4.0/timeout.rb:33:in `catch'\", \"/var/vcap/data/packages/ruby-2.4-r5/697e94aad1386999dbb4b0076540305ec07c12 9a/lib/ruby/2.4.0/timeout.rb:108:in `timeout'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/cloud_controller_ng/app/jobs/timeout_job.rb:12:in `perform'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a 65dd828af0f5ed52633be1f8c3a269e0/cloud_controller_ng/app/jobs/wrapping_job.rb:11:in `perform'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/cloud_controller_ng/app/jobs/logging_context_job.rb:17:in `block in p erform'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/cloud_controller_ng/app/jobs/logging_context_job.rb:63:in `with_request_id_set'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed5263 3be1f8c3a269e0/cloud_controller_ng/app/jobs/logging_context_job.rb:15:in `perform'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:81:in `bl ock in invoke_job'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'\", \"/var/vcap/data/packages/cloud_controller_ng /15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job- 4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:78:in `invoke_job'\", \"/var/vcap/data/ packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:230:in `block (2 levels) in run'\", \"/var/vcap/data/packages/ruby-2.4-r5/697e94aad1386999dbb4b0076540305ec07c129a/lib /ruby/2.4.0/timeout.rb:93:in `block in timeout'\", \"/var/vcap/data/packages/ruby-2.4-r5/697e94aad1386999dbb4b0076540305ec07c129a/lib/ruby/2.4.0/timeout.rb:103:in `timeout'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f 8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:230:in `block in run'\", \"/var/vcap/data/packages/ruby-2.4-r5/697e94aad1386999dbb4b0076540305ec07c129a/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'\", \"/var/vcap/data/packages /cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:229:in `run'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gem s/delayed_job-4.1.5/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:213:in `block in work_off'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:212:in `times'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:212:in `work_off'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:175:in `block (4 levels) in start'\", \"/var/vcap/data/packages/ruby-2.4-r5/697e94aad1386999dbb4b0076540305ec07c129a/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:174:in `block (3 levels) in start'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:173:in `block (2 levels) in start'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:172:in `loop'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:172:in `block in start'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `block in add'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:171:in `start'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/cloud_controller_ng/lib/tasks/jobs.rake:71:in `start_working'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/cloud_controller_ng/lib/tasks/jobs.rake:43:in `block (2 levels) in <top (required)>'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'\", \"/var/vcap/data/packages/ruby-2.4-r5/697e94aad1386999dbb4b0076540305ec07c129a/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'\", \"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/gem_home/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'\", \"/var/vcap/packages/cloud_controller_ng/gem_home/ruby/2.4.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'\", \"/var/vcap/packages/cloud_controller_ng/gem_home/ruby/2.4.0/bin/rake:23:in `load'\", \"/var/vcap/packages/cloud_controller_ng/gem_home/ruby/2.4.0/bin/rake:23:in `<top (required)>'\", \"/var/vcap/data/packages/ruby-2.4-r5/697e94aad1386999dbb4b0076540305ec07c129a/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:74:in `load'\", \"/var/vcap/data/packages/ruby-2.4-r5/697e94aad1386999dbb4b0076540305ec07c129a/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:74:in `kernel_load'\", \"/var/vcap/data/packages/ruby-2.4-r5/697e94aad1386999dbb4b0076540305ec07c129a/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:28:in `run'\", \"/var/vcap/data/packages/ruby-2.4-r5/697e94aad1386999dbb4b0076540305ec07c129a/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:424:in `exec'\", \"/var/vcap/data/packages/ruby-2.4-r5/697e94aad1386999dbb4b0076540305ec07c129a/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'\", \"/var/vcap/data/packages/ruby-2.4-r5/697e94aad1386999dbb4b0076540305ec07c129a/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'\", \"/var/vcap/data/packages/ruby-2.4-r5/697e94aad1386999dbb4b0076540305ec07c129a/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'\", \"/var/vcap/data/packages/ruby-2.4-r5/697e94aad1386999dbb4b0076540305ec07c129a/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:27:in `dispatch'\", \"/var/vcap/data/packages/ruby-2.4-r5/697e94aad1386999dbb4b0076540305ec07c129a/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'\", \"/var/vcap/data/packages/ruby-2.4-r5/697e94aad1386999dbb4b0076540305ec07c129a/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:18:in `start'\", \"/var/vcap/packages/ruby-2.4-r5/bin/bundle:30:in `block in <main>'\", \"/var/vcap/data/packages/ruby-2.4-r5/697e94aad1386999dbb4b0076540305ec07c129a/lib/ruby/site_ruby/2.4.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'\", \"/var/vcap/packages/ruby-2.4-r5/bin/bundle:22:in `<main>'\"]}}","log_level":"error","source":"cc.background","data":{"request_guid":"54045705-64d4-41e4-5084-08092a10b21c::f9e4e016-9811-48c8-95cd-73934feae275","job_guid":"e0aedb65-dde3-4d79-a666-51f7dabfa037"},"thread_id":46952060505960,"fiber_id":46952104354120,"process_id":1,"file":"/var/vcap/data/packages/cloud_controller_ng/15a3557a65dd828af0f5ed52633be1f8c3a269e0/cloud_controller_ng/app/jobs/logging_context_job.rb","lineno":43,"method":"block in log_error"}
```

## Possible Fix

Update the bits-service client code to maybe not report an internal server error? Or at least report an error message that more clearly indicates what went wrong?

**Comment by tcdowney** [comment]
Main difference between the [bits-service-client](https://github.com/cloudfoundry-incubator/bits-service-client) and our own internal `DavClient` here is that the bits-service-client will raise an error in `delete_blob` when there is a 404 and our `DavClient` will just log and return.

bits-service-client:
https://github.com/cloudfoundry-incubator/bits-service-client/blob/4a63cd7b8a7e5909084d6d2bff1ac8228fcca319/lib/bits_service_client/client.rb#L102

Internal DavClient:
https://github.com/cloudfoundry/cloud_controller_ng/blob/e0c95989f1f196316fbcc83a227076b2bc6b9fe3/lib/cloud_controller/blobstore/webdav/dav_client.rb#L147

The `fog-google` client also no-ops when it gets a 404 back:
https://github.com/fog/fog-google/blob/490b3e4cb9aabb44bd480f6a315f214caa551a6d/lib/fog/storage/google_json/models/file.rb#L69

I think we should PR the bits-service-client to make it behave the same as the others.

**Comment by tcdowney** [comment]
@emalm 

Since this was discovered by a team trying to integrate with Eirini and is a bigger deal in that configuration is this something y'all might be able to contribute to the bits-service client gem?

**Comment by emalm** [comment]
Thanks, @tcdowney, @jenspinney and I will coordinate to track this.

**Comment by cwlbraa** [comment]
I don't think this is relevant any longer...
