### ISSUE TITLE
issue with postgres :  the script db.rake doesnt create the extension citext

### ISSUE THREAD

**Issue by addisflava** [cloudfoundry/cloud_controller_ng#1409]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue
the command on line 67 of db.rake  fails and i have to do it manually
 
grep -n "{db_config.name} -c '#{extensions}" /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/cloud_controller_ng/lib/tasks/db.rake

```
ccdb1014=> \dx
                 List of installed extensions
  Name   | Version |   Schema   |         Description          
---------+---------+------------+------------------------------
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(1 row)

ccdb1014=> CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION
ccdb1014=> \dx
                           List of installed extensions
  Name   | Version |   Schema   |                   Description                    
---------+---------+------------+--------------------------------------------------
 citext  | 1.5     | public     | data type for case-insensitive character strings
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)

```

the error on /var/vcap/sys/log/cloud_controller_ng/pre-start.stderr.log

```
[2019-08-09 20:34:41+0000] + bundle exec rake db:migrate
[2019-08-09 20:34:50+0000] rake aborted!
[2019-08-09 20:34:50+0000] Sequel::DatabaseError: PG::UndefinedObject: ERROR:  type "citext" does not exist
[2019-08-09 20:34:50+0000] LINE 1: ...IMESTAMP NOT NULL, "updated_at" Timestamp, "name" CIText NOT...
[2019-08-09 20:34:50+0000]                                                              ^
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:152:in `async_exec'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:152:in `block in execute_query'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/database/logging.rb:38:in `log_connection_yield'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:152:in `execute_query'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:140:in `block in execute'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:116:in `check_disconnect_errors'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:140:in `execute'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:496:in `_execute'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:314:in `block (2 levels) in execute'
4:in `block (2 levels) in execute'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:518:in `check_database_errors'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:314:in `block in execute'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/connection_pool/threaded.rb:88:in `hold'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/database/connecting.rb:270:in `synchronize'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:314:in `execute'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/database/query.rb:50:in `execute_dui'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/database/query.rb:43:in `execute_ddl'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/database/schema_methods.rb:682:in `create_table_from_generator'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/database/schema_methods.rb:194:in `create_table'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/cloud_controller_ng/db/migrations/20130131184954_new_initial_schema.rb:57:in `block (2 levels) in <top (required)>'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/extensions/migration.rb:107:in `instance_exec'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/extensions/migration.rb:107:in `apply'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/extensions/migration.rb:684:in `block (2 levels) in run'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/database/transactions.rb:245:in `_transaction'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/database/transactions.rb:220:in `block in transaction'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/database/connecting.rb:270:in `synchronize'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/database/transactions.rb:186:in `transaction'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/extensions/migration.rb:475:in `checked_transaction'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/extensions/migration.rb:683:in `block in run'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/extensions/migration.rb:680:in `each'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/extensions/migration.rb:680:in `run'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/extensions/migration.rb:402:in `run'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/cloud_controller_ng/lib/cloud_controller/db_migrator.rb:18:in `apply_migrations'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/cloud_controller_ng/lib/tasks/db.rake:178:in `migrate'
[2019-08-09 20:34:50+0000] /var/vcap/data/packages/cloud_controller_ng/8e2b3e80d969f28168605fc64f7618ac283d83ef/cloud_controller_ng/lib/tasks/db.rake:36:in `block (2 levels) in <top (required)>'
[2019-08-09 20:34:50+0000] /var/vcap/packages/cloud_controller_ng/gem_home/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
[2019-08-09 20:34:50+0000] /var/vcap/packages/ruby-2.5.5-r0.10.0/bin/bundle:30:in `block in <main>'
[2019-08-09 20:34:50+0000] /var/vcap/packages/ruby-2.5.5-r0.10.0/bin/bundle:22:in `<main>'
[provide quick introduction so this issue can be triaged]
```
## Context

[provide more detailed introduction]

## Steps to Reproduce

[ordered list the process to finding and recreating the issue, example below]

## Expected result

[describe what you would expect to have resulted from this process]

## Current result

[describe what you are currently experiencing from this process, and thereby explain the bug]

[include relevant logs]

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by cwlbraa** [comment]
Interesting! Does this fail when you run via our bosh deployment? What are you trying to do that you ran into this?
