### ISSUE TITLE
`cf push` returns 500 when using Eirini/OPI

### ISSUE THREAD

**Issue by jenspinney** [cloudfoundry/cloud_controller_ng#1411]
## Issue

As of CAPI release v1.85.0, running `cf push` when using OPI instead of Diego returns a 500 error.

Specifically, the `/v3/processes/<GUID>/stats` endpoint is returning an HTTP 500 error. The logs indicate the error description is "no member 'host_tls_proxy_port' in struct". (Stack trace details are below).

## Context

We are deploying the cloud controller with `opi_enabled = true`. When the `/v3/processes/<GUID>/stats` endpoint is hit, we see the following stacktrace in our CC logs:

```
{"errors"=>[{"title"=>"UnknownError", "detail"=>"An unknown error occurred.", "code"=>10001, "test_mode_info"=>{"detail"=>"no member 'host_tls_proxy_port' in struct", "title"=>"CF-host_tls_proxy_port", "backtrace"=>
["/var/vcap/data/packages/cloud_controller_ng/4c2f21d9cd895028c36ac8254af00000ea6d229b/cloud_controller_ng/app/presenters/v3/process_stats_presenter.rb:80:in `[]'", 
"/var/vcap/data/packages/cloud_controller_ng/4c2f21d9cd895028c36ac8254af00000ea6d229b/cloud_controller_ng/app/presenters/v3/process_stats_presenter.rb:80:in `block in net_info_to_instance_ports'", 
"/var/vcap/data/packages/cloud_controller_ng/4c2f21d9cd895028c36ac8254af00000ea6d229b/cloud_controller_ng/app/presenters/v3/process_stats_presenter.rb:76:in `map'", 
"/var/vcap/data/packages/cloud_controller_ng/4c2f21d9cd895028c36ac8254af00000ea6d229b/cloud_controller_ng/app/presenters/v3/process_stats_presenter.rb:76:in `net_info_to_instance_ports'", 
"/var/vcap/data/packages/cloud_controller_ng/4c2f21d9cd895028c36ac8254af00000ea6d229b/cloud_controller_ng/app/presenters/v3/process_stats_presenter.rb:67:in `add_port_info'", 
"/var/vcap/data/packages/cloud_controller_ng/4c2f21d9cd895028c36ac8254af00000ea6d229b/cloud_controller_ng/app/presenters/v3/process_stats_presenter.rb:51:in `block in found_instance_stats_hash'", 
"/var/vcap/data/packages/cloud_controller_ng/4c2f21d9cd895028c36ac8254af00000ea6d229b/cloud_controller_ng/app/presenters/v3/process_stats_presenter.rb:51:in `tap'", 
"/var/vcap/data/packages/cloud_controller_ng/4c2f21d9cd895028c36ac8254af00000ea6d229b/cloud_controller_ng/app/presenters/v3/process_stats_presenter.rb:51:in `found_instance_stats_hash'", 
"/var/vcap/data/packages/cloud_controller_ng/4c2f21d9cd895028c36ac8254af00000ea6d229b/cloud_controller_ng/app/presenters/v3/process_stats_presenter.rb:29:in `instance_stats_hash'", 
"/var/vcap/data/packages/cloud_controller_ng/4c2f21d9cd895028c36ac8254af00000ea6d229b/cloud_controller_ng/app/presenters/v3/process_stats_presenter.rb:18:in `block in present_stats_hash'", 
"/var/vcap/data/packages/cloud_controller_ng/4c2f21d9cd895028c36ac8254af00000ea6d229b/cloud_controller_ng/app/presenters/v3/process_stats_presenter.rb:17:in `each'", 
"/var/vcap/data/packages/cloud_controller_ng/4c2f21d9cd895028c36ac8254af00000ea6d229b/cloud_controller_ng/app/presenters/v3/process_stats_presenter.rb:17:in `map'", 
"/var/vcap/data/packages/cloud_controller_ng/4c2f21d9cd895028c36ac8254af00000ea6d229b/cloud_controller_ng/app/presenters/v3/process_stats_presenter.rb:17:in `present_stats_hash'", 
"/var/vcap/data/packages/cloud_controller_ng/4c2f21d9cd895028c36ac8254af00000ea6d229b/cloud_controller_ng/app/presenters/v3/process_stats_presenter.rb:12:in `to_hash'", "/var/vcap/data/packages/cloud_controller_ng/4c2f21d9cd895028c36ac8254af00000ea6d229b/gem_home/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/core_ext/object/json.rb:54:in `as_json'", 
"/var/vcap/data/packages/cloud_controller_ng/4c2f21d9cd895028c36ac8254af00000ea6d229b/cloud_controller_ng/config/initializers/json.rb:14:in `encode'",
```

(the stacktrace continues, but I believe all the info you need is already above)

We think this is because [this commit](https://github.com/cloudfoundry/cloud_controller_ng/commit/b8c22f25714cec75bc6bbe0afa50ac736061b081) introduced an assumption that the `net_info` struct has a `host_tls_proxy_port` property, which is defined in the diego model [here](https://github.com/cloudfoundry/cloud_controller_ng/blob/0b5b46a2c9a6ba021a1c18b3aa8a96222fb28d11/lib/diego/bbs/models/actual_lrp_pb.rb#L16). However, the [OPI equivalent](https://github.com/cloudfoundry/cloud_controller_ng/blob/0b5b46a2c9a6ba021a1c18b3aa8a96222fb28d11/lib/cloud_controller/opi/instances_client.rb#L32) does not define this property.

## Steps to Reproduce
1. Deploy CF with Eirini (using [`eirini-bosh-release`](https://github.com/cloudfoundry-community/eirini-bosh-release) or [`eirini-release`](https://github.com/cloudfoundry-incubator/eirini-release)) using CAPI v1.85.0.
1. `cf push any-app`
1. See it fail.

## Expected result

`cf push` should exit with code 0 and we should observe the app running. This worked in CAPI v1.84.0.

## Current result
This was the result of our `cf push` attempt:

```
   -----> Copy binaries to app/bin directory
   Exit status 0
   Uploading droplet, build artifacts cache...
   Uploading droplet...
   Uploading build artifacts cache...
   Uploaded build artifacts cache (2M)
   Uploaded droplet (23M)
   Uploading complete
   Cell caf52ce3-82fb-46e9-afdb-a1f08f081042 stopping instance 4fc577e7-4abb-40c8-a0ee-4a37f991558c
   Cell caf52ce3-82fb-46e9-afdb-a1f08f081042 destroying container for instance 4fc577e7-4abb-40c8-a0ee-4a37f991558c

Waiting for app to start...

Unexpected Response
Response Code: 500
Request ID:    0555d70d-35de-4278-7b82-d9c9f1537313::da2a1a91-a835-4c00-84cc-63a80d287cc6
Code: 0, Title: , Detail: {
  "errors": [
    {
      "title": "UnknownError",
      "detail": "An unknown error occurred.",
      "code": 10001
    }
  ]
}
FAILED
```

## Possible Fix

Change the code in `app/presenters/v3/process_stats_presenter.rb` to allow the new `net_info` properties to be optional.

Thanks,
Jen + @jrussett

**Comment by selzoc** [comment]
Oooooh, good catch!  As you know we're currently working on adding Eirini to a CI environment.  We can fix this for you in our next release.
