### ISSUE TITLE
"cf7 push --strategy rolling" fails when a health check timeout is configured in manifest

### ISSUE THREAD

**Issue by stephanme** [cloudfoundry/cloud_controller_ng#1425]
## Issue

Rolling update (cf7 push --strategy rolling) fails when a health check timeout is configured in manifest and the app has 2 instances.

## Context

cf-deployment 11.0.0
cf cli v7.0.0-beta.24

Simple hello-world type app using staticfile_buildpack with 2 instances:

```
$ ls
index.html  manifest.yml  README.md  Staticfile
$ cat manifest.yml
---
applications:
- name: staticfile-test
  memory: 256M
  instances: 2
  buildpacks:
  - staticfile_buildpack
  random-route: true
```

## Steps to Reproduce

I can successfully deploy and update this application using ZDM update:
```
$ cf7 --version
cf7 version 7.0.0-beta.24+71d763254.2019-08-20
$ cf7 api
api endpoint:   https://api.cf.sap.hana.ondemand.com
api version:    2.139.0

$ cf7 push
Using manifest file /c/Users/d047883/git/staticfile-sample/manifest.yml
Applying manifest...
Manifest applied
Pushing app staticfile-test to org uptime / space uptimeci as D047883...
...
Waiting for app staticfile-test to start...

name:              staticfile-test
requested state:   started
routes:            staticfile-test-excellent-gazelle.cfapps.sap.hana.ondemand.com
last uploaded:     Tue 27 Aug 17:57:45 DST 2019
stack:             cflinuxfs3
buildpacks:        staticfile

type:            web
instances:       2/2
memory usage:    256M
start command:   $HOME/boot.sh
     state     since                  cpu    memory      disk      details
#0   running   2019-08-27T15:57:58Z   0.0%   0 of 256M   0 of 1G
#1   running   2019-08-27T15:57:58Z   0.0%   0 of 256M   0 of 1G


$ cf7 push --strategy rolling
Using manifest file /c/Users/d047883/git/staticfile-sample/manifest.yml
Applying manifest...
Manifest applied
Pushing app staticfile-test to org uptime / space uptimeci as D047883...
...
Starting deployment for app staticfile-test...
Waiting for app to deploy...

name:              staticfile-test
requested state:   started
routes:            staticfile-test-excellent-gazelle.cfapps.sap.hana.ondemand.com
last uploaded:     Tue 27 Aug 18:03:18 DST 2019
stack:             cflinuxfs3
buildpacks:        staticfile

type:            web
instances:       2/2
memory usage:    256M
start command:   $HOME/boot.sh
     state     since                  cpu    memory          disk         details
#0   running   2019-08-27T16:03:33Z   4.7%   11.3M of 256M   5.3M of 1G
#1   running   2019-08-27T16:03:43Z   0.0%   0 of 256M       0
```

All good so far.

Now I add a health check timeout to the manifest:

```
$ cat manifest.yml
---
applications:
- name: staticfile-test
  memory: 256M
  instances: 2
  buildpacks:
  - staticfile_buildpack
  random-route: true
  timeout: 90 # added
```

And run again a rolling update:

```
$ cf7 push --strategy rolling
Using manifest file /c/Users/d047883/git/staticfile-sample/manifest.yml
Applying manifest...
Manifest applied
Pushing app staticfile-test to org uptime / space uptimeci as D047883...
...
Starting deployment for app staticfile-test...
Waiting for app to deploy...
Start app timeout

TIP: Application must be listening on the right port. Instead of hard coding the port, use the $PORT environment variable.

Use 'cf7 logs staticfile-test --recent' for more information
FAILED

$ cf7 app staticfile-test
Showing health and status for app staticfile-test in org uptime / space uptimeci as D047883...

name:              staticfile-test
requested state:   started
routes:            staticfile-test-excellent-gazelle.cfapps.sap.hana.ondemand.com
last uploaded:     Tue 27 Aug 18:05:33 DST 2019
stack:             cflinuxfs3
buildpacks:        staticfile

type:           web
instances:      2/2
memory usage:   256M
     state     since                  cpu    memory          disk         details
#0   running   2019-08-27T16:03:34Z   0.4%   11.3M of 256M   5.3M of 1G
#1   running   2019-08-27T16:03:44Z   1.2%   11.2M of 256M   5.3M of 1G

type:           web
instances:      1/1
memory usage:   256M
     state     since                  cpu    memory          disk         details
#0   running   2019-08-27T16:05:46Z   1.0%   11.3M of 256M   5.3M of 1G
```

## Expected result

cf7 push --strategy rolling succeeds.

## Current result

The deployment got stuck after the first new instance is running (see above).
The deployment is still running:
```
$ cf7 app staticfile-test --guid
bd835782-2f96-48e7-8d44-9c3dd5b9a876
$ cf7 curl /v3/deployments?app_guids=bd835782-2f96-48e7-8d44-9c3dd5b9a876
...
     {
         "guid": "ec5da62f-7963-4392-9d32-3b9cfe92fadc",
         "state": "DEPLOYING",
         "status": {
            "value": "DEPLOYING",
            "reason": null,
            "details": {
               "last_successful_healthcheck": "2019-08-27T16:05:37Z"
            }
         },

```

In the cloud controller logs I find this stack trace when searching for the deployment guid:
```
ingestor_message:<14>1 2019-08-27T17:03:01.805507Z 10.0.65.107 cc_deployment_updater rs2 - [instance@47450 director="bosh-aws-canary" deployment="cf" group="scheduler" az="z1" id="b0ef3865-5bd2-4af3-b5ca-d5fd1109c238"] {"timestamp":1566925381.4185264,"message":"error-scaling-deployment","log_level":"error","source":"cc.deployment_updater.update","data":{"deployment_guid":"ec5da62f-7963-4392-9d32-3b9cfe92fadc","error":"VCAP::CloudController::Config::InvalidConfigPath","error_message":"\"maximum_health_check_timeout\" is not a valid config key","backtrace":"/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/cloud_controller_ng/lib/cloud_controller/config.rb:138:in `invalid_config_path!'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/cloud_controller_ng/lib/cloud_controller/config.rb:130:in `block in valid_config_path?'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/cloud_controller_ng/lib/cloud_controller/config.rb:126:in `each'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/cloud_controller_ng/lib/cloud_controller/config.rb:126:in `valid_config_path?'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/cloud_controller_ng/lib/cloud_controller/config.rb:116:in `get'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/cloud_controller_ng/app/models/runtime/constraints/health_check_policy.rb:20:in `validate_timeout'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/cloud_controller_ng/app/models/runtime/constraints/health_check_policy.rb:10:in `validate'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/cloud_controller_ng/app/models/runtime/process_model.rb:259:in `map'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/cloud_controller_ng/app/models/runtime/process_model.rb:259:in `validate'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1876:in `block in _valid?'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1015:in `around_validation'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1873:in `_valid?'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1833:in `block in _save_valid?'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1893:in `checked_save_failure'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1833:in `_save_valid?'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1461:in `save'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1478:in `save_changes'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:2049:in `update_restricted'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1579:in `update'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/cloud_controller_ng/lib/cloud_controller/deployment_updater/updater.rb:134:in `scale_down_oldest_web_process_with_instances'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/cloud_controller_ng/lib/cloud syslog_message:{"timestamp":1566925381.4185264,"message":"error-scaling-deployment","log_level":"error","source":"cc.deployment_updater.update","data":{"deployment_guid":"ec5da62f-7963-4392-9d32-3b9cfe92fadc","error":"VCAP::CloudController::Config::InvalidConfigPath","error_message":"\"maximum_health_check_timeout\" is not a valid config key","backtrace":"/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/cloud_controller_ng/lib/cloud_controller/config.rb:138:in `invalid_config_path!'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/cloud_controller_ng/lib/cloud_controller/config.rb:130:in `block in valid_config_path?'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/cloud_controller_ng/lib/cloud_controller/config.rb:126:in `each'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/cloud_controller_ng/lib/cloud_controller/config.rb:126:in `valid_config_path?'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/cloud_controller_ng/lib/cloud_controller/config.rb:116:in `get'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/cloud_controller_ng/app/models/runtime/constraints/health_check_policy.rb:20:in `validate_timeout'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/cloud_controller_ng/app/models/runtime/constraints/health_check_policy.rb:10:in `validate'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/cloud_controller_ng/app/models/runtime/process_model.rb:259:in `map'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/cloud_controller_ng/app/models/runtime/process_model.rb:259:in `validate'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1876:in `block in _valid?'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1015:in `around_validation'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1873:in `_valid?'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1833:in `block in _save_valid?'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1893:in `checked_save_failure'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1833:in `_save_valid?'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1461:in `save'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1478:in `save_changes'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:2049:in `update_restricted'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/gem_home/ruby/2.5.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1579:in `update'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/cloud_controller_ng/lib/cloud_controller/deployment_updater/updater.rb:134:in `scale_down_oldest_web_process_with_instances'
/var/vcap/data/packages/cloud_controller_ng/f8fa8c3670051f129432dc68b5dc168c8924fc6d/cloud_controller_ng/lib/cloud ingestor_timestamp:August 27th 2019, 17:03:01.913 tags:kafka bosh_az:z1 syslog_facility:user-level syslog_msgid:- retention_period:7d syslog_hostname:10.0.65.107 syslog_shipper:cc_deployment_updater bosh_deployment:cf bosh_director:bosh-aws-canary syslog_severity:informational @type:unknown ingestor_type:syslog @timestamp:August 27th 2019, 17:03:01.805 syslog_timestamp:August 27th 2019, 17:03:01.805 syslog_procid:rs2 bosh_id:b0ef3865-5bd2-4af3-b5ca-d5fd1109c238 bosh_group:scheduler _id:CnMH1GwBwcAj6i7k8Ogd _type:_doc _index:logstash-2019.08.27-7d _score: -
```

Such logs continue until I cancel the deployment.

I can't reproduce this issue when the application has only 1 instance.

**Comment by cwlbraa** [comment]
Fixed in capi-release 1.85.0 👍 Thanks!

https://www.pivotaltracker.com/n/projects/966314/stories/167446891
