### ISSUE TITLE
cf create-buildpack dotnet failed sometimes and return 422 buildpack zipfile is not valid

### ISSUE THREAD

**Issue by zhanggbj** [cloudfoundry/cloud_controller_ng#1433]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

This doesn't happen 100%, usually after 1 successful uploading, others will fail with 422 buildpack zipfile is not valid. 

## Context

When I go to CC log, it shows
```
{"timestamp":1568193421.7206903,"message":"Completed 200 vcap-request-id: 40ad4f76-46cb-4697-ab9e-2467ed419a5d","log_level":"info","source":"cc.api","data":{"request_guid":"40ad4f76-46cb-4697-ab9e-2467ed419a5d"},"thread_id":47061667806960,"fiber_id":47061690817440,"process_id":6,"file":"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/cloud_controller_ng/middleware/request_logs.rb","lineno":24,"method":"call"}
{"timestamp":1568193421.7210639,"message":"blobstore.cp-finish","log_level":"info","source":"cc.blobstore","data":{"request_guid":"894a322a-4dc4-439b-9da7-b83fb181f695","destination_key":"9dad3ee3-14d7-47e6-92ca-96ece7a2a30b_8efbaca7d0aba2668077b6e4190a0a79a900bf10ae6749f42c259eba3211f25d","duration_seconds":32.837274565,"size":1192108822},"thread_id":47061692750960,"fiber_id":47061690539020,"process_id":6,"file":"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/cloud_controller_ng/lib/cloud_controller/blobstore/fog/fog_client.rb","lineno":78,"method":"cp_to_blobstore"}
{"timestamp":1568193421.7239208,"message":"Request failed: 422: {\"description\"=>\"Buildpack zip error: buildpack zipfile is not valid\", \"error_code\"=>\"CF-BuildpackZipError\", \"code\"=>390013, \"test_mode_info\"=>{\"description\"=>\"Buildpack zip error: buildpack zipfile is not valid\", \"error_code\"=>\"CF-BuildpackZipError\", \"backtrace\"=>[\"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/cloud_controller_ng/lib/cloud_controller/upload_buildpack.rb:74:in `rescue in determine_new_stack'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/cloud_controller_ng/lib/cloud_controller/upload_buildpack.rb:70:in `determine_new_stack'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/cloud_controller_ng/lib/cloud_controller/upload_buildpack.rb:28:in `upload_buildpack'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/cloud_controller_ng/app/controllers/runtime/buildpack_bits_controller.rb:33:in `upload'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/cloud_controller_ng/app/controllers/base/base_controller.rb:86:in `dispatch'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/cloud_controller_ng/lib/cloud_controller/rest_controller/routes.rb:16:in `block in define_route'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1634:in `call'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1634:in `block in compile!'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block (3 levels) in route!'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1011:in `route_eval'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block (2 levels) in route!'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1040:in `block in process_route'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `catch'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `process_route'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:990:in `block in route!'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:989:in `each'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:989:in `route!'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1097:in `block in dispatch!'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `catch'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1094:in `dispatch!'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `block in call!'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `catch'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `call!'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:913:in `call'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/rack-protection-2.0.5/lib/rack/protection/xss_header.rb:18:in `call'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/rack-protection-2.0.5/lib/rack/protection/path_traversal.rb:16:in `call'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/rack-protection-2.0.5/lib/rack/protection/json_csrf.rb:26:in `call'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/rack-protection-2.0.5/lib/rack/protection/frame_options.rb:31:in `call'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/rack-2.0.7/lib/rack/null_logger.rb:9:in `call'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:194:in `call'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1957:in `call'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/rack-2.0.7/lib/rack/urlmap.rb:68:in `block in call'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/rack-2.0.7/lib/rack/urlmap.rb:53:in `each'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/rack-2.0.7/lib/rack/urlmap.rb:53:in `call'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/cloud_controller_ng/middleware/request_logs.rb:22:in `call'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/cloud_controller_ng/middleware/security_context_setter.rb:19:in `call'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/cloud_controller_ng/middleware/vcap_request_id.rb:15:in `call'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/cloud_controller_ng/middleware/cors.rb:49:in `call_app'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/cloud_controller_ng/middleware/cors.rb:14:in `call'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/cloud_controller_ng/middleware/request_metrics.rb:12:in `call'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:153:in `call'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:50:in `block in process'\", \"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/gem_home/ruby/2.5.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:1067:in `block in spawn_threadpool'\"]}}","log_level":"info","source":"cc.api","data":{"request_guid":"894a322a-4dc4-439b-9da7-b83fb181f695"},"thread_id":47061692750960,"fiber_id":47061690539020,"process_id":6,"file":"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/cloud_controller_ng/lib/sinatra/vcap.rb","lineno":44,"method":"block in registered"}
```

There's a cli known issue here https://github.com/cloudfoundry/cli/issues/1544, but the error in CC is also weird.

## Steps to Reproduce

```
$ cf version
cf version 6.41.0+dd4c76cdd.2018-11-28
```
```
CF_TRACE=true cf create-buildpack test buildpack_dotnet-core_v2.3-20190609-2145.zip 9999

PUT /v2/buildpacks/12620daf-cd0c-4133-a37a-86fc87a4349d/bits HTTP/1.1
Host: api.bcfd-vpc-szr-440802.us-south.containers.appdomain.cloud
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: multipart/form-data; boundary=0803e4d9a686869df748781456e4b847611cdac42d1babefd42c37de1007
User-Agent: cf/6.41.0+dd4c76cdd.2018-11-28 (go1.11.2; amd64 linux)
[multipart/form-data Content Hidden]

 1.11 GiB / 1.11 GiB [=============================================================================================================================================================================================================] 100.00%

error seeking a stream on retry: Put https://api.bcfd-vpc-szr-440802.us-south.containers.appdomain.cloud/v2/buildpacks/12620daf-cd0c-4133-a37a-86fc87a4349d/bits: EOF
FAILED

## Expected result

[describe what you would expect to have resulted from this process]

## Current result

[describe what you are currently experiencing from this process, and thereby explain the bug]

[include relevant logs]


## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by cwlbraa** [comment]
This is a very interesting failure mode, it looks like the buildpack isn't getting all the way up there, and so that's the error we would expect.

Buildpacks take an interesting route to the blobstore. They're uploaded by the cli, through the gorouter, to the nginx that fronts the cc api. The nginx writes these large files to disk, then the cc processes them, finds their stack, and uploads them to the blobstore. 

What's strange is that the nginx side of the cli->nginx leg doesn't seem to fail hard enough to prevent the ruby code from continuing onwards with the buildpack upload. Can you find any record of this upload in your nginx logs?

**Comment by zhanggbj** [comment]
@cwlbraa 
Thanks a lot for the info.

1) could you please help explain the "interesting route to the blobstore", we have s special DNS, not sure if this will impact it.

2) Here is the log to create build in **CC** and **nginx**, or do you need any other log files, please let me know, thanks!

```
./cloud_controller_ng.log:4499:{"timestamp":1568627613.2744505,"message":"Started POST \"/v2/buildpacks\" for user: 729c6d49-b038-45bb-8b39-25ca06fa6a8e, ip: 10.240.0.12 with vcap-request-id: b40f69a8-1dd0-4623-a9b1-95596402a571 at 2019-09-16 09:53:33 UTC","log_level":"info","source":"cc.api","data":{"request_guid":"b40f69a8-1dd0-4623-a9b1-95596402a571"},"thread_id":47377829534060,"fiber_id":47377822477280,"process_id":7,"file":"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/cloud_controller_ng/middleware/request_logs.rb","lineno":12,"method":"call"}
./cloud_controller_ng.log:4500:{"timestamp":1568627613.2960515,"message":"Completed 201 vcap-request-id: b40f69a8-1dd0-4623-a9b1-95596402a571","log_level":"info","source":"cc.api","data":{"request_guid":"b40f69a8-1dd0-4623-a9b1-95596402a571"},"thread_id":47377829534060,"fiber_id":47377822477280,"process_id":7,"file":"/var/vcap/packages/.src/523ebc2180cae1e4555359313bbdf35175ba2fc0/cloud_controller_ng/middleware/request_logs.rb","lineno":24,"method":"call"}
./nginx-access.log:2231:api.bcfd-vpc-dev1513.us-south.containers.appdomain.cloud - [16/Sep/2019:09:53:33 +0000] "POST /v2/buildpacks HTTP/1.1" 201 708 "-" "cf/6.41.0+dd4c76cdd.2018-11-28 (go1.11.2; amd64 linux)" 10.240.0.12, 172.30.181.30 vcap_request_id:b40f69a8-1dd0-4623-a9b1-95596402a571 userid:729c6d49-b038-45bb-8b39-25ca06fa6a8e clientid:cf response_time:0.104
```

**Comment by zhanggbj** [comment]
Using **cf7** resolved this issue.
