### ISSUE TITLE
CC-Worker should fail/stop if a migration is not completed yet

### ISSUE THREAD

**Issue by jochenehret** [cloudfoundry/cloud_controller_ng#1510]
## Issue
If there is CC database migration running (during update) the cc-workers should fail or stop if the migration is failing or taking too much time (timeout).
Currently the cloud_controller_ng job checks continuously if a migration is running:
``` LOG
Sequel::Migrator::NotCurrentError: migrator is not current
/var/vcap/data/packages/cloud_controller_ng/67976ce6eefc2a19eecfc9d57ff9ab2373334dbe/gem_home/ruby/2.5.0/gems/sequel-5.22.0/lib/sequel/extensions/migration.rb:376:in `check_current'
/var/vcap/data/packages/cloud_controller_ng/67976ce6eefc2a19eecfc9d57ff9ab2373334dbe/cloud_controller_ng/lib/cloud_controller/db_migrator.rb:29:in `check_migrations!'
/var/vcap/data/packages/cloud_controller_ng/67976ce6eefc2a19eecfc9d57ff9ab2373334dbe/cloud_controller_ng/lib/cloud_controller/db.rb:52:in `load_models'
/var/vcap/data/packages/cloud_controller_ng/67976ce6eefc2a19eecfc9d57ff9ab2373334dbe/cloud_controller_ng/lib/cloud_controller/background_job_environment.rb:12:in `setup_environment'
/var/vcap/data/packages/cloud_controller_ng/67976ce6eefc2a19eecfc9d57ff9ab2373334dbe/cloud_controller_ng/lib/tasks/jobs.rake:59:in `start_working'
/var/vcap/data/packages/cloud_controller_ng/67976ce6eefc2a19eecfc9d57ff9ab2373334dbe/cloud_controller_ng/lib/tasks/jobs.rake:43:in `block (2 levels) in <top (required)>'
/var/vcap/packages/cloud_controller_ng/gem_home/ruby/2.5.0/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'
/var/vcap/packages/ruby-2.5.5-r0.10.0/bin/bundle:30:in `block in <main>'
/var/vcap/packages/ruby-2.5.5-r0.10.0/bin/bundle:22:in `<main>'
Tasks: TOP => jobs:generic
(See full trace by running task with --trace)
rake aborted!
```
Furthermore the CPU load increases to 100%.

## Context

We were updating from CF v12.3.0 to v12.9.0 which included a database scheme migration. The migration failed because of database issues, but the cc-workers were updated anyway. They started to fail because they expected the new database scheme.

## Steps to Reproduce

See above.

## Expected result

cc-worker should fail so that BOSH stops the update.

## Current result

All cc-workers are updated and shown as "running" in BOSH.

## Possible Fix

The "cloud_controller_worker" job should fail so that BOSH can see that there is a problem.

Related issue: https://github.com/cloudfoundry/cloud_controller_ng/issues/1363

**Comment by cwlbraa** [comment]
started a thread to discuss this here in #cf-deployment: https://cloudfoundry.slack.com/archives/C2U7KA7M4/p1579722394000500
