### ISSUE TITLE
CF-InvalidValue during cf-push

### ISSUE THREAD

**Issue by kramerul** [cloudfoundry/cloud_controller_ng#1533]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

We tried to run the cloud_controller_ng in a quarks environment using the capi-k8s-release. After several steps we ended up with the following problem when running `cf push`:

```
{"timestamp":1578568378.4905496,"message":"Request failed: 500: {\"error_code\"=>\"UnknownError\", \"description\"=>\"An unknown error occurred.\", \"code\"=>10001, \"test_mode_info\"=>{\"description\"=>\"ArgumentError: mon out of range\", \"error_code\"=>\"CF-InvalidValue\"
```

## Context

Same configuration as in #1532 

## Steps to Reproduce

* Install cloudfoudry using quarks
* Install `capi-k8s-release` with a few changes
* run `cf push`

## Expected result

No error

## Current result

After adding some instrumentation code, it turned out that the value, which caused the problem was `0000-00-00 00:00:00`

```
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/core.rb:285:in `rescue in string_to_datetime'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/core.rb:275:in `string_to_datetime'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/timezones.rb:136:in `convert_input_timestamp'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/timezones.rb:77:in `convert_timestamp'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/database/misc.rb:300:in `to_application_timestamp'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/adapters/mysql.rb:349:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/adapters/mysql.rb:349:in `block in yield_rows'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/adapters/mysql.rb:349:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/adapters/mysql.rb:349:in `yield_rows'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/adapters/mysql.rb:296:in `block in fetch_rows'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/adapters/mysql.rb:169:in `_execute'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/adapters/utils/mysql_mysql2.rb:39:in `block in execute'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/connection_pool/threaded.rb:88:in `hold'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/database/connecting.rb:270:in `synchronize'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/adapters/utils/mysql_mysql2.rb:39:in `execute'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/dataset/actions.rb:1088:in `execute'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/adapters/mysql.rb:336:in `execute'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/adapters/mysql.rb:281:in `fetch_rows'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/dataset/actions.rb:941:in `with_sql_each'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/dataset/actions.rb:949:in `with_sql_first'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/model/base.rb:1728:in `_refresh_get'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/model/base.rb:1800:in `_save_refresh'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/model/base.rb:1757:in `block (2 levels) in _save'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/model/base.rb:1015:in `around_create'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/model/base.rb:1750:in `block in _save'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/model/base.rb:1015:in `around_save'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/model/base.rb:1745:in `_save'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/model/base.rb:1465:in `block (2 levels) in save'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/model/base.rb:1905:in `block in checked_transaction'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/database/transactions.rb:229:in `block in transaction'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/connection_pool/threaded.rb:88:in `hold'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/database/connecting.rb:270:in `synchronize'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/database/transactions.rb:199:in `transaction'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/model/base.rb:1905:in `checked_transaction'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/model/base.rb:1465:in `block in save'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/model/base.rb:1893:in `checked_save_failure'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/model/base.rb:1465:in `save'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:19:in `block (2 levels) in enqueue_job'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:17:in `block in enqueue_job'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:16:in `tap'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:16:in `enqueue_job'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:12:in `enqueue'
/cloud_controller_ng/app/jobs/enqueuer.rb:39:in `enqueue_job'
/cloud_controller_ng/app/jobs/enqueuer.rb:15:in `enqueue'
/cloud_controller_ng/app/actions/package_upload.rb:19:in `block in upload_async'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/database/transactions.rb:258:in `_transaction'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/database/transactions.rb:233:in `block in transaction'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/database/connecting.rb:270:in `synchronize'
/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/database/transactions.rb:199:in `transaction'
/cloud_controller_ng/app/actions/package_upload.rb:11:in `upload_async'
/cloud_controller_ng/app/actions/package_upload.rb:30:in `upload_async_without_event'
/cloud_controller_ng/app/controllers/runtime/app_bits_upload_controller.rb:55:in `upload'
/cloud_controller_ng/app/controllers/base/base_controller.rb:84:in `dispatch'
/cloud_controller_ng/lib/cloud_controller/rest_controller/routes.rb:16:in `block in define_route'
/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1634:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1634:in `block in compile!'
/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1011:in `route_eval'
/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1040:in `block in process_route'
/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `catch'
/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `process_route'
/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:990:in `block in route!'
/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:989:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:989:in `route!'
/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1097:in `block in dispatch!'
/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'
/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `catch'
/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'
/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1094:in `dispatch!'
/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `block in call!'
/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'
/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `catch'
/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'
/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `call!'
/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:913:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/rack-protection-2.0.5/lib/rack/protection/xss_header.rb:18:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/rack-protection-2.0.5/lib/rack/protection/path_traversal.rb:16:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/rack-protection-2.0.5/lib/rack/protection/json_csrf.rb:26:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/rack-protection-2.0.5/lib/rack/protection/frame_options.rb:31:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.0.8/lib/rack/null_logger.rb:9:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.0.8/lib/rack/head.rb:12:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:194:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1957:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.0.8/lib/rack/urlmap.rb:68:in `block in call'
/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.0.8/lib/rack/urlmap.rb:53:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.0.8/lib/rack/urlmap.rb:53:in `call'
/cloud_controller_ng/middleware/request_logs.rb:22:in `call'
/cloud_controller_ng/middleware/security_context_setter.rb:19:in `call'
/cloud_controller_ng/middleware/vcap_request_id.rb:15:in `call'
/cloud_controller_ng/middleware/cors.rb:49:in `call_app'
/cloud_controller_ng/middleware/cors.rb:14:in `call'
/cloud_controller_ng/middleware/request_metrics.rb:12:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.0.8/lib/rack/builder.rb:153:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
/usr/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
/usr/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
/usr/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:50:in `block in process'
/usr/local/lib/ruby/gems/2.5.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:1067:in `block in spawn_threadpool'
```

## Possible Fix

After adding the following line at `/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/core.rb:276` the problem no longer occurred. But this is definitely not the right approach.

```
return Time.now() if string == '0000-00-00 00:00:00'
```

**Comment by cwlbraa** [comment]
```/cloud_controller_ng/app/actions/package_upload.rb:11:in `upload_async'
/cloud_controller_ng/app/actions/package_upload.rb:30:in `upload_async_without_event'
/cloud_controller_ng/app/controllers/runtime/app_bits_upload_controller.rb:55:in `upload'
```

suggests that this is probably due to the lack of nginx upload module in that release.

**Comment by sethboyles** [comment]
@kramerul is this still and issue for you with newer versions of capi-k8s-release?  I believe this has been resolved, but wanted to double check before I closed the issue.

**Comment by kramerul** [comment]
No we haven't faced this issue in the last time.
