### ISSUE TITLE
"staging_upload_password" config value does not support special characters.

### ISSUE THREAD

**Issue by bonzofenix** [cloudfoundry/cloud_controller_ng#245]
CC distributed on cf_release v170 does not supports staging_upload_password with special characters such as '@':

```json
{"timestamp":1400265376.8369846,"message":"Request failed: 500: {\"code\"=>10001, \"description\"=>\"bad component(expected user component): p@ssword\", \"error_code\"=>\"CF-InvalidComponentError\", \"backtrace\"=>[\"/var/vcap/packages/ruby/lib/ruby/1.9.1/uri/generic.rb:439:in `check_password'\", \"/var/vcap/packages/ruby/lib/ruby/1.9.1/uri/generic.rb:389:in `check_userinfo'\", \"/var/vcap/packages/ruby/lib/ruby/1.9.1/uri/generic.rb:454:in `userinfo='\", \"/var/vcap/packages/ruby/lib/ruby/1.9.1/uri/generic.rb:193:in `initialize'\", \"/var/vcap/packages/ruby/lib/ruby/1.9.1/uri/http.rb:84:in `initialize'\", \"/var/vcap/packages/ruby/lib/ruby/1.9.1/uri/generic.rb:140:in `new'\", \"/var/vcap/packages/ruby/lib/ruby/1.9.1/uri/generic.rb:140:in `build'\", \"/var/vcap/packages/ruby/lib/ruby/1.9.1/uri/http.rb:62:in `build'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/blobstore/url_generator.rb:55:in `staging_uri'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/blobstore/url_generator.rb:49:in `generate_download_url'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/blobstore/url_generator.rb:14:in `app_package_download_url'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/app_stager_task.rb:99:in `staging_request'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/app_stager_task.rb:86:in `block in stage'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/cache/cf-message-bus-cb951d204bee/lib/eventmachine/schedule_sync.rb:16:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/cache/cf-message-bus-cb951d204bee/lib/eventmachine/schedule_sync.rb:16:in `block in schedule_sync'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:250:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:250:in `block in schedule'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:959:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:959:in `block in run_deferred_callbacks'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:956:in `times'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:956:in `run_deferred_callbacks'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/runner.rb:76:in `run!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/bin/cloud_controller:12:in `<main>'\"]}","log_level":"error","source":"cc.api","data":{"request_guid":"f783f1c538a9639f653d436f870b8be7::daf0b9d6-885b-4561-93d0-0ab1f7e10221"},"thread_id":55625220,"fiber_id":46299460,"process_id":3856,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/sinatra/vcap.rb","lineno":53,"method":"block in registered"}
``` 

Also as @jbayer mentioned in  [this thread](https://mail.google.com/mail/u/0/#inbox/145fb6f89ed2bf82) it might worth adding  **staging_upload_user** and
**staging_upload_password** in the [conf file](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/config/cloud_controller.yml " ads") .

**Comment by dieucao** [comment]
This was fixed a while back.
https://github.com/cloudfoundry/cloud_controller_ng/commit/6604a34fd53a9504c0e06e0892cbc0c8175b58b6
