### ISSUE TITLE
Updating a service broker with incompatible catalog fails with UnknownError, swallowing root cause details

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cloud_controller_ng#2538]
## Issue

Updating a service broker with incompatible catalog fails with UnknownError, swallowing root cause message

## Context

As a cloudfoundry operator
* in order to quickly understand when a service broker catalog change is incompatible
* I need a clear root cause message to be displayed

## Steps to Reproduce

with capi-release version: 1.111.0 despite fix for related https://github.com/cloudfoundry/cloud_controller_ng/issues/2147

* Given a service broker catalog has a change in planid with the same name
* try trying to update the broker, then it fails with a swallowed root cause
```
$ cf update-service-broker my-broker user login url

```

## Expected result

The root cause should be displayed, in this case `Plan names must be unique within a service. Service xx already has a plan named yy`

## Current result

trying to update the broker, then it fails with a swallowed root cause
```
$ cf update-service-broker my-broker user login url

Job (f387a4be-08a4-4f1e-b6fd-f07e6f6adda4) failed: An unknown error occurred.

FAILED
```

Relevant logs

```
$bosh ssh cc-worker/0

$ cat /var/vcap/sys/log/cloud_controller_worker/cloud_controller_worker.log

{"timestamp":"2021-10-13T15:15:06.116963106Z","message":"Request failed: 500: {\"error_code\"=>\"UnknownError\", \"description\"=>\"An unknown error occurred.\", \"code\"=>10001, \"test_mode_info\"=>{\"description\"=>\"Plan names must be unique within a service. Service xx already has a plan named yy\", \"error_code\"=>\"CF-InvalidServiceBroker\", \"backtrace\"=>[\"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/cloud_controller_ng/app/jobs/v3/services/update_broker_job.rb:74:in `rescue in perform'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/cloud_controller_ng/app/jobs/v3/services/update_broker_job.rb:66:in `perform'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/cloud_controller_ng/app/jobs/v3/services/update_broker_job.rb:17:in `perform'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/cloud_controller_ng/app/jobs/wrapping_job.rb:13:in `perform'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/cloud_controller_ng/app/jobs/wrapping_job.rb:13:in `perform'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/cloud_controller_ng/app/jobs/timeout_job.rb:13:in `block in perform'\", \"/var/vcap/data/packages/ruby-2.7.2-r0.41.0/ef05b738c21f38ac007c3000d14fffcc6db27d88/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'\", \"/var/vcap/data/packages/ruby-2.7.2-r0.41.0/ef05b738c21f38ac007c3000d14fffcc6db27d88/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'\", \"/var/vcap/data/packages/ruby-2.7.2-r0.41.0/ef05b738c21f38ac007c3000d14fffcc6db27d88/lib/ruby/2.7.0/timeout.rb:33:in `catch'\", \"/var/vcap/data/packages/ruby-2.7.2-r0.41.0/ef05b738c21f38ac007c3000d14fffcc6db27d88/lib/ruby/2.7.0/timeout.rb:33:in `catch'\", \"/var/vcap/data/packages/ruby-2.7.2-r0.41.0/ef05b738c21f38ac007c3000d14fffcc6db27d88/lib/ruby/2.7.0/timeout.rb:110:in `timeout'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/cloud_controller_ng/app/jobs/timeout_job.rb:12:in `perform'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f
7c8d30323ce52c2a/cloud_controller_ng/app/jobs/wrapping_job.rb:13:in `perform'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/cloud_controller_ng/app/jobs/logging_context_job.rb:17:in `block in perform'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/cloud_controller_ng/app/jobs/logging_context_job.rb:67:in `with_request_id_set'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/cloud_controller_ng/app/jobs/logging_context_job.rb:15:in `perform'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/backend/base.rb:81:in `block in invoke_job'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:61:in `block in initialize'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:66:in `execute'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/rub
y/2.7.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:40:in `run_callbacks'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/backend/base.rb:78:in `invoke_job'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:230:in `block (2 levels) in run'\", \"/var/vcap/data/packages/ruby-2.7.2-r0.41.0/ef05b738c21f38ac007c3000d14fffcc6db27d88/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'\", \"/var/vcap/data/packages/ruby-2.7.2-r0.41.0/ef05b738c21f38ac007c3000d14fffcc6db27d88/lib/ruby/2.7.0/timeout.rb:105:in `timeout'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home
/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:230:in `block in run'\", \"/var/vcap/data/packages/ruby-2.7.2-r0.41.0/ef05b738c21f38ac007c3000d14fffcc6db27d88/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:229:in `run'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'\", \"/var/vcap/data/packages/clou
d_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:61:in `block in initialize'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:66:in `execute'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:40:in `run_callbacks'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:213:in `block in work_off'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:212:in `times'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:212:in `work_off'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:175:in `block (4 levels) in start'\", \"/var/vcap/dat
a/packages/ruby-2.7.2-r0.41.0/ef05b738c21f38ac007c3000d14fffcc6db27d88/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:174:in `block (3 levels) in start'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:61:in `block in initialize'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:66:in `execute'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:40:in `run_callbacks'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:173:in `block (2 levels) in start'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:172:in `loop'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:172:in `block in start'\", \"/var/vcap/data/packages/cloud_controll
er_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:61:in `block in initialize'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:79:in `block in add'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:66:in `execute'\",  \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:40:in `run_callbacks'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:171:in `start'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/cloud_controller_ng/lib/tasks/jobs.rake:76:in `start_working'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/cloud_controller_ng/lib/tasks/jobs.rake:49:in `block (2 levels) in <top (required)>'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:279:in `block in execute'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:279:in `each'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:279:in `execute'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/honeycomb-beeline-2.4.0/lib/honeycomb/integrations/rake.rb:14:in `execute'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `synchronize'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:160:in `invoke_task'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:83:in `block in run'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:80:in `run'\", \"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'\", \"/var/vcap/packages/cloud_controller_ng/gem_home/ruby/2.7.0/bin/rake:23:in `load'\", \"/var/vcap/packages/cloud_controller_ng/gem_home/ruby/2.7.0/bin/rake:23:in `<top (required)>'\", \"/var/vcap/data/packages/ruby-2.7.2-r0.41.0/ef05b738c21f38ac007c3000d14fffcc6db27d88/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:63:in `load'\", \"/var/vcap/data/packages/ruby-2.7.2-r0.41.0/ef05b738c21f38ac007c3000d14fffcc6db27d88/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'\", \"/var/vcap/data/packages/ruby-2.7.2-r0.41.0/ef05b738c21f38ac007c3000d14fffcc6db27d88/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:28:in `run'\", \"/var/vcap/data/packages/ruby-2.7.2-r0.41.0/ef05b738c21f38ac007c3000d14fffcc6db27d88/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:476:in `exec'\", \"/var/vcap/data/packages/ruby-2.7.2-r0.41.0/ef05b738c21f38ac007c3000d14fffcc6db27d88/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'\", \"/var/vcap/data/packages/ruby-2.7.2-r0.41.0/ef05b738c21f38ac007c3000d14fffcc6db27d88/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'\", \"/var/vcap/data/packages/ruby-2.7.2-r0.41.0/ef05b738c21f38ac007c3000d14fffcc6db27d88/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'\", \"/var/vcap/data/packages/ruby-2.7.2-r0.41.0/ef05b738c21f38ac007c3000d14fffcc6db27d88/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:30:in `dispatch'\", \"/var/vcap/data/packages/ruby-2.7.2-r0.41.0/ef05b738c21f38ac007c3000d14fffcc6db27d88/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'\", \"/var/vcap/data/packages/ruby-2.7.2-r0.41.0/ef05b738c21f38ac007c3000d14fffcc6db27d88/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:24:in `start'\", \"/var/vcap/data/packages/ruby-2.7.2-r0.41.0/ef05b738c21f38ac007c3000d14fffcc6db27d88/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'\", \"/var/vcap/data/packages/ruby-2.7.2-r0.41.0/ef05b738c21f38ac007c3000d14fffcc6db27d88/lib/ruby/site_ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'\", \"/var/vcap/data/packages/ruby-2.7.2-r0.41.0/ef05b738c21f38ac007c3000d14fffcc6db27d88/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'\", \"/var/vcap/packages/ruby-2.7.2-r0.41.0/bin/bundle:23:in`load'\", \"/var/vcap/packages/ruby-2.7.2-r0.41.0/bin/bundle:23:in `<main>'\"]}}","log_level":"error","source":"cc.background","data":{"request_guid":"59f53f1f-3d0d-4f4c-4b14-96e8cb6faa18::742743e0-3df9-4ffe-bd05-dfa78b6f68a4","job_guid":"60939330-f5bc-4483-9bd6-e988a5545d4c"},"thread_id":66800,fiber_id":66960,"process_id":5,"file":"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/cloud_controller_ng/app/jobs/logging_context_job.rb","lineno":47,"method":"block in log_error"}{"timestamp":"2021-10-13T15:15:06.135812253Z","message":"2021-10-13T15:15:06+0000: [Worker(cc_global_worker.cc-worker.0.1)] Job service_broker.update (id=469430) (queue=cc-generic) FAILED (0 prior attempts) with VCAP::CloudController::V3::ServiceBrokerUpdate::InvalidServiceBroker: Plan names must be unique within a service. Service xx already has a plan namedyy","log_level":"error","source":"cc-worker","data":{},"thread_id":66800,"fiber_id":66960,"process_id":5,"file":"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb","lineno":285,"method":"say"}{"timestamp":"2021-10-13T15:15:06.136938300Z","message":"2021-10-13T15:15:06+0000: [Worker(cc_global_worker.cc-worker.0.1)] Job service_broker.update (id=469430) (queue=cc-generic) FAILED permanently because of 1 consecutive failures","log_level":"error","source":"cc-worker","data":{},"thread_id":66800,"fiber_id":66960,"process_id":5,"file":"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb","lineno":285,"method":"say"}{"timestamp":"2021-10-13T15:15:06.151397393Z","message":"2021-10-13T15:15:06+0000: [Worker(cc_global_worker.cc-worker.0.1)] 1 jobs processed at 1.6727 j/s, 1 failed","log_level":"info","source":"cc-worker","data":{},"thread_id":66800,"fiber_id":66960,"process_id":5,"file":"/var/vcap/data/packages/cloud_controller_ng/9cec37e430e29597db74106f7c8d30323ce52c2a/gem_home/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb","lineno":285,"method":"say"}
```

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by gberche-orange** [comment]
I'll try to reproduce against capi 1.119.0 and will report back the status.

**Comment by philippthun** [comment]
Possible fix: #2537

**Comment by gberche-orange** [comment]
thanks @philippthun ! I'm looking forward to your pr being merged and released

**Comment by sweinstein22** [comment]
Hi @gberche-orange ,

This looks like the same issue as https://github.com/cloudfoundry/cloud_controller_ng/issues/2504. We've made a change that should remedy the issue, which will go out in the next cloud controller release. At that point if upgrading does not fix things feel free to reopen this issue. Thanks!
