### ISSUE TITLE
Data too long for column 'handler'

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cloud_controller_ng#338]
We're running release v200.

We had a customer with an application that had 15000 some odd files in it.  When attempting to push this application with the CLI it would take a long time to upload and eventually fail with a 400 error.

Looking at the logs I see the error below.  This error appears to be a side effect to the main problem but figured I'd log this issue anyway since you probably don't want to put too much data in the handler column regardless.

```
{"timestamp":1426798989.3684545,"message":"Mysql2::Error: Data too long for column 'handler' at row 1: INSERT INTO `delayed_jobs` (`queue`, `handler`, `priority`, `created_at`, `run_at`, `guid`) VALUES ('cc-cloud_controller_pz2-0', '--- !ruby/object:VCAP::CloudController::Jobs::ExceptionCatchingJob\\nhandler: !ruby/object:VCAP::CloudController::Jobs::RequestJob\\n  handler: !ruby/object:VCAP::CloudController::Jobs::TimeoutJob\\n    handler: !ruby/object:VCAP::CloudController::Jobs::Runtime::AppBitsPacker\\n      app_guid: 013ec716-dcd6-4a9a-aecc-ced9b973efd9\\n      uploaded_compressed_path: \\\"/var/vcap/data/cloud_controller_ng/tmp/uploads/0000011202\\\"\\n      fingerprints:\\n      - fn: client/src/libs/handlebars/handlebars.amd.js\\n        sha1: b6caf4b2277988b432cf4b721aaf908796f9a6ba\\n        size: 93973\\n      - fn: client/src/libs/handlebars/handlebars.js\\n        sha1: f5740f775fc0ff1809a6833099ed83b0896cd093\\n        size: 89667\\n      - fn: node_modules/body-parser/node_modules/type-is/node_modules/mime-types/lib/mime.json\\n        sha1: 9d615e63f2e7bff607d455be4e3db73a07191bdb\\n        size: 71165\\n      - fn: node_modules/chai/chai.js\\n        sha1: 80a81da918cc1a355fd23c104379920817ef5b78\\n        size: 121651\\n      - fn: node_modules/compression/node_modules/accepts/node_modules/mime-types/node_modules/mime-db/db.json\\n        sha1: e0dbf7ff9a51f988de6426931c37f862ccc5cf74\\n        size: 137031\\n      - fn: node_modules/compression/node_modules/compressible/node_modules/mime-db/db.json\\n        sha1: e0dbf7ff9a51f988de6426931c37f862ccc5cf74\\n        size: 137031\\n      - fn: node_modules/express/node_modules/accepts/node_modules/mime-types/node_modules/mime-db/db.json\\n        sha1: 674bad384ed3d31daaa982f471d71d2c15783633\\n        size: 136052\\n      - fn: node_modules/express/node_modules/type-is/node_modules/mime-types/node_modules/mime-db/db.json\\n        sha1: 674bad384ed3d31daaa982f471d71d2c15783633\\n        size: 136052\\n      - fn: node_modules/express-handlebars/node_modules/glob/oh-my-glob.gif\\n        sha1: d6e03eb580c508e65722e0216ba439449aec1a3a\\n        size: 510360\\n      - fn: node_modules/express-handlebars/node_modules/handlebars/coverage/coverage.json\\n        sha1: 8d3f5c01dfe98e9c0ef5fd5153d5aec2cb087fd5\\n        size: 257097\\n      - fn: node_modules/express-handlebars/node_modules/handlebars/coverage/lcov-report/dist/cjs/handlebars/compiler/javascript-compiler.js.html\\n        sha1: 6fcfc91d5bbde8fc43b278fcd629e3b3b2320292\\n        size: 90618\\n      - fn: node_modules/express-handlebars/node_modules/handlebars/coverage/lcov-report/dist/cjs/handlebars/compiler/parser.js.html\\n        sha1: 461a6c7a7726e216723c6771b85ae3654f3c0620\\n        size: 69499\\n      - fn: node_modules/express-handlebars/node_modules/handlebars/coverage/lcov-report/spec/helpers.js.html\\n        sha1: 7061bca26f026a7897d593648314bb210eda3591\\n        size: 94931\\n      - fn: node_modules/express-handlebars/node_modules/handlebars/dist/handlebars.amd.js\\n        sha1: 4ddcb8fb62777ad8478f4db942579a3f5e277147\\n        size: 105493\\n      - fn: node_modules/...","log_level":"error","source":"cc.db","data":{"request_guid":"d340c76a-44a0-497b-79f4-b37661f77bc4::20743e6a-35b3-4e33-9558-de9475dff661"},"thread_id":69822882265600,"fiber_id":69822903225080,"process_id":2820,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sequel-4.17.0/lib/sequel/database/logging.rb","lineno":70,"method":"block in log_each"}
{"timestamp":1426798989.3704767,"message":"exception not translated: Sequel::DatabaseError - Mysql2::Error: Data too long for column 'handler' at row 1:\\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sequel-4.17.0/lib/sequel/adapters/mysql2.rb:77:in `query'\\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sequel-4.17.0/lib/sequel/adapters/mysql2.rb:77:in `block in _execute'\\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sequel-4.17.0/lib/sequel/database/logging.rb:37:in `log_yield'\\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sequel-4.17.0/lib/sequel/adapters/mysql2.rb:77:in `_execute'\\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sequel-4.17.0/lib/sequel/adapters/shared/mysql_prepared_statements.rb:34:in `block in execute'\\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sequel-4.17.0/lib/sequel/database/connecting.rb:250:in `block in synchronize'\\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sequel-4.17.0/lib/sequel/connection_pool/threaded.rb:85:in `hold'\\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sequel-4.17.0/lib/sequel/database/connecting.rb:250:in `synchronize'\\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sequel-4.17.0/lib/sequel/adapters/shared/mysql_prepared_statements.rb:34:in `execute'\\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sequel-4.17.0/lib/sequel/adapters/mysql2.rb:61:in `execute_insert'\\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sequel-4.17.0/lib/sequel/dataset/actions.rb:922:in `execute_insert'\\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sequel-4.17.0/lib/sequel/dataset/actions.rb:335:in `insert'\\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sequel-4.17.0/lib/sequel/model/base.rb:1814:in `_insert_raw'\\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sequel-4.17.0/lib/sequel/model/base.rb:1796:in `_insert'\\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sequel-4.17.0/lib/sequel/model/base.rb:1856:in `block (2 levels) in _save'\\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sequel-4.17.0/lib/sequel/model/base.rb:1124:in `around_create'\\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sequel-4.17.0/lib/sequel/model/base.rb:1853:in `block in _save'\\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sequel-4.17.0/lib/sequel/model/base.rb:1124:in `around_save'\\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sequel-4.17.0/lib/sequel/mo...","log_level":"warn","source":"cc.api","data":{"request_guid":"d340c76a-44a0-497b-79f4-b37661f77bc4::20743e6a-35b3-4e33-9558-de9475dff661"},"thread_id":69822882265600,"fiber_id":69822903225080,"process_id":2820,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/app/controllers/base/base_controller.rb","lineno":260,"method":"translate_and_log_exception"}
{"timestamp":1426798989.371948,"message":"Request failed: 400: {\"code\"=>10004, \"description\"=>\"The request is invalid\", \"error_code\"=>\"CF-InvalidRequest\", \"backtrace\"=>[\"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/app/controllers/base/base_controller.rb:82:in `rescue in dispatch'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/app/controllers/base/base_controller.rb:74:in `dispatch'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/rest_controller/routes.rb:16:in `block in define_route'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1602:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1602:in `block in compile!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'\", \"/var/vcap/packages/cloud_cont...","log_level":"info","source":"cc.api","data":{"request_guid":"d340c76a-44a0-497b-79f4-b37661f77bc4::20743e6a-35b3-4e33-9558-de9475dff661"},"thread_id":69822882265600,"fiber_id":69822903225080,"process_id":2820,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/sinatra/vcap.rb","lineno":51,"method":"block in registered"}
```

**Comment by dieucao** [comment]
@youngm 
Thanks for the report.
This was fixed in cf-release v201
https://www.pivotaltracker.com/story/show/89572944

**Comment by youngm** [comment]
Oh good.  Thanks Dieu!

**Comment by dieucao** [comment]
@youngm Another thing to consider is tweaking what file size triggers resource matching.
