### ISSUE TITLE
DEA advertise causes flood of blobstore requests

### ISSUE THREAD

**Issue by fraenkel** [cloudfoundry/cloud_controller_ng#437]
When a DEA registers for the first time via the NATS 'staging.advertise', CC responds with a NATS 'buildpack' response.

In the small, this doesn't seem bad, but when you have 30 CCs, 400 DEAs and 15 buildpacks, this creates a nightmare. Each DEA will broadcast to each CC which will intern generate the 15 buildpack URIs. If we just focus on 1 DEA, this is 30 x 15 = 450 requests.
When a CC is restarted, it will respond to all 400 DEAs since it has no record of them, the requests to the objectstore become 400 x 15 = 6000 requests per CC. If each request takes .5s, that will be a minimum of 6000 / 20 * .5 = 150s.

During this 150s, the CC will be unresponsive and monit at times will become unhappy and restart CC.
This is also happening across all the CCs as they are restarted.

There are a few problems identified, some easier to fix than others.
1. Numerous calls to the blobstore to obtain the buildpack uris.
2. Having all N CC's respond to a staging.advertise with a buildpack is nice but overkill

Solutions
1. We should remember the list of files from the blobstore once rather than doing it multiple times when the list does not change.
2. CCs and DEAs should be able to compute a simple SHA of the known buildpacks without going to the blobstore.
3. A DEA can determine if it needs to request the buildpack URIs.
4. DEAs should request the buildpack uris rather than blindly have them sent by all CCs.

```
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/excon-0.44.1/lib/excon/socket.rb:134:in `select'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/excon-0.44.1/lib/excon/socket.rb:134:in `rescue in block in connect'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/excon-0.44.1/lib/excon/socket.rb:114:in `block in connect'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/excon-0.44.1/lib/excon/socket.rb:110:in `each'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/excon-0.44.1/lib/excon/socket.rb:110:in `connect'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/excon-0.44.1/lib/excon/ssl_socket.rb:150:in `connect'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/excon-0.44.1/lib/excon/socket.rb:28:in `initialize'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/excon-0.44.1/lib/excon/ssl_socket.rb:8:in `initialize'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/excon-0.44.1/lib/excon/connection.rb:387:in `new'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/excon-0.44.1/lib/excon/connection.rb:387:in `socket'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/excon-0.44.1/lib/excon/connection.rb:106:in `request_call'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/excon-0.44.1/lib/excon/middlewares/mock.rb:47:in `request_call'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/excon-0.44.1/lib/excon/middlewares/instrumentor.rb:22:in `request_call'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/excon-0.44.1/lib/excon/middlewares/base.rb:15:in `request_call'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/excon-0.44.1/lib/excon/middlewares/base.rb:15:in `request_call'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/excon-0.44.1/lib/excon/middlewares/base.rb:15:in `request_call'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/excon-0.44.1/lib/excon/connection.rb:233:in `request'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/fog-core-1.28.0/lib/fog/core/connection.rb:63:in `request'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/fog-1.27.0/lib/fog/openstack/storage.rb:149:in `request'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/fog-1.27.0/lib/fog/openstack/requests/storage/head_object.rb:12:in `head_object'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/fog-1.27.0/lib/fog/openstack/models/storage/files.rb:84:in `head'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/blobstore/client.rb:138:in `file'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/blobstore/client.rb:122:in `blob'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/blobstore/client.rb:117:in `download_uri'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/blobstore/url_generator.rb:72:in `generate_download_url'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/blobstore/url_generator.rb:30:in `admin_buildpack_download_url'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/admin_buildpacks_presenter.rb:17:in `admin_buildpack_entry'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/admin_buildpacks_presenter.rb:10:in `block in to_staging_message_array'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/admin_buildpacks_presenter.rb:10:in `collect'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/admin_buildpacks_presenter.rb:10:in `to_staging_message_array'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/dea/stager_pool.rb:53:in `admin_buildpacks'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/dea/stager_pool.rb:49:in `publish_buildpacks'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/dea/stager_pool.rb:18:in `process_advertise_message'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/dea/stager_pool.rb:44:in `block in register_subscriptions'",
        "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/cf-message-bus-0.3.3/lib/cf_message_bus/message_bus.rb:88:in `yield'",
```

**Comment by dieucao** [comment]
@fraenkel Okay to close this issue?  I believe all the PRs were merged.

**Comment by fraenkel** [comment]
Yup. Closed.
