### ISSUE TITLE
Cloud controller failed to install buildpacks

### ISSUE THREAD

**Issue by jianghaitao** [cloudfoundry/cloud_controller_ng#443]
I would like to have some suggestion or help in terms of how to fix following cloud controller error related to buildpacks
```
{"timestamp":1443637085.7370925,"message":"Installing buildpack nodejs_buildpack","log_level":"info","source":"cc.background","data":{},"thread_id":70072448725800,"fiber_id":70072484272320,"process_id":25835,"file":"/var/vcap/data/packages/cloud_controller_ng/9b84bcc79ce079128bb3a06c360d465eb83ad0d1.1-e1f5c42acc35263dcf1fae16376ac1526c1e59e8/cloud_controller_ng/app/jobs/runtime/buildpack_installer.rb","lineno":15,"method":"perform"}
{"timestamp":1443637086.2412286,"message":"Buildpack nodejs_buildpack failed to install or update. Error: #<NoMethodError: undefined method `lock!' for nil:NilClass>","log_level":"error","source":"cc.background","data":{},"thread_id":70072448725800,"fiber_id":70072484272320,"process_id":25835,"file":"/var/vcap/data/packages/cloud_controller_ng/9b84bcc79ce079128bb3a06c360d465eb83ad0d1.1-e1f5c42acc35263dcf1fae16376ac1526c1e59e8/cloud_controller_ng/app/jobs/runtime/buildpack_installer.rb","lineno":38,"method":"rescue in perform"}
```
This happened to all buildpacks

Thanks

**Comment by zrob** [comment]
Hi @jianghaitao 

we took a look at the code that manages this and did not see anything that jumped out at us.  

the most likely reason I can think of that would cause issues with uploading buildpacks would be if your blobstore settings are misconfigured.  can you verify if you are able to connect to your blobstore from the cloud controller using the values you have configured?

thanks,
@zrob & @jeffpak93

**Comment by jeffpak93** [comment]
Hi @jianghaitao ,

We haven't heard back from you in a while. Do you have any news regarding being able to connect to your blobstore from the CC using the values you've configured? Let us know! 

thanks,
@jeffpak93 & @jberkhahn , CF CAPI Team

**Comment by rmasand** [comment]
Hi @jianghaitao, 

Going to close this issue since we haven't heard back from you. Feel free to reopen if you'd like to continue discussing it.

Thanks,

Raina Masand
CAPI Team

**Comment by ronakbanka** [comment]
Hi @zrob 

we have a existing deployment using cf v220 , which was upgraded to this version.

Now with same manifest when i am trying to create another deployment , i am facing this buildpack installation issues 

```
{"timestamp":1458664098.1791651,"message":"Buildpack staticfile_buildpack failed to install or update. Error: #<NoMethodError: undefined method `lock!' for nil:NilClass>","log_level":"error","source":"cc.background","data":{},"thread_id":70193027185040,"fiber_id":70193051853720,"process_id":3264,"file":"/var/vcap/data/packages/cloud_controller_ng/405c21e6b5094a7e5d35868d44a6427e655e6d4d.1-1ffca2f9fcdb2df71a5ecdfee63fe4a27178542e/cloud_controller_ng/app/jobs/runtime/buildpack_installer.rb","lineno":38,"method":"rescue in perform"}
{"timestamp":1458664098.180574,"message":"Request failed: 500: {\"code\"=>10001, \"description\"=>\"undefined method `lock!' for nil:NilClass\", \"error_code\"=>\"CF-NoMethodError\", \"backtrace\"=>[\"/var/vcap/data/packages/cloud_controller_ng/405c21e6b5094a7e5d35868d44a6427e655e6d4d.1-1ffca2f9fcdb2df71a5ecdfee63fe4a27178542e/cloud_controller_ng/app/models/runtime/buildpack.rb:19:in `before_save'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/sequel-4.21.0/lib/sequel/model/base.rb:1871:in `block in _save'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/sequel-4.21.0/lib/sequel/model/base.rb:1124:in `around_save'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/sequel-4.21.0/lib/sequel/model/base.rb:1869:in `_save'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/sequel-4.21.0/lib/sequel/model/base.rb:1549:in `block (2 levels) in save'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/sequel-4.21.0/lib/sequel/model/base.rb:2032:in `block in checked_transaction'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/sequel-4.21.0/lib/sequel/database/transactions.rb:134:in `_transaction'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/sequel-4.21.0/lib/sequel/database/transactions.rb:108:in `block in transaction'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/sequel-4.21.0/lib/sequel/database/connecting.rb:250:in `block in synchronize'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/sequel-4.21.0/lib/sequel/connection_pool/threaded.rb:98:in `hold'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/sequel-4.21.0/lib/sequel/database/connecting.rb:250:in `synchronize'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/sequel-4.21.0/lib/sequel/database/transactions.rb:97:in `transaction'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/sequel-4.21.0/lib/sequel/model/base.rb:2032:in `checked_transaction'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/sequel-4.21.0/lib/sequel/model/base.rb:1549:in `block in save'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/sequel-4.21.0/lib/sequel/model/base.rb:2020:in `checked_save_failure'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/sequel-4.21.0/lib/sequel/model/base.rb:1549:in `save'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/sequel-4.21.0/lib/sequel/model/base.rb:148:in `create'\", \"/var/vcap/data/packages/cloud_controller_ng/405c21e6b5094a7e5d35868d44a6427e655e6d4d.1-1ffca2f9fcdb2df71a5ecdfee63fe4a27178542e/cloud_controller_ng/app/jobs/runtime/buildpack_installer.rb:19:in `perform'\", \"/var/vcap/data/packages/cloud_controller_ng/405c21e6b5094a7e5d35868d44a6427e655e6d4d.1-1ffca2f9fcdb2df71a5ecdfee63fe4a27178542e/cloud_controller_ng/app/jobs/wrapping_job.rb:9:in `perform'\", \"/var/vcap/data/packages/cloud_controller_ng/405c21e6b5094a7e5d35868d44a6427e655e6d4d.1-1ffca2f9fcdb2df71a5ecdfee63fe4a27178542e/cloud_controller_ng/app/jobs/timeout_job.rb:7:in `block in perform'\", \"/var/vcap/packages/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'\", \"/var/vcap/packages/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:32:in `block in catch'\", \"/var/vcap/packages/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:32:in `catch'\", \"/var/vcap/packages/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:32:in `catch'\", \"/var/vcap/packages/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:103:in `timeout'\", \"/var/vcap/data/packages/cloud_controller_ng/405c21e6b5094a7e5d35868d44a6427e655e6d4d.1-1ffca2f9fcdb2df71a5ecdfee63fe4a27178542e/cloud_controller_ng/app/jobs/timeout_job.rb:6:in `perform'\", \"/var/vcap/data/packages/cloud_controller_ng/405c21e6b5094a7e5d35868d44a6427e655e6d4d.1-1ffca2f9fcdb2df71a5ecdfee63fe4a27178542e/cloud_controller_ng/app/jobs/request_job.rb:13:in `perform'\", \"/var/vcap/data/packages/cloud_controller_ng/405c21e6b5094a7e5d35868d44a6427e655e6d4d.1-1ffca2f9fcdb2df71a5ecdfee63fe4a27178542e/cloud_controller_ng/app/jobs/wrapping_job.rb:9:in `perform'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/backend/base.rb:94:in `block in invoke_job'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/lifecycle.rb:61:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/lifecycle.rb:61:in `block in initialize'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/lifecycle.rb:66:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/lifecycle.rb:66:in `execute'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/lifecycle.rb:40:in `run_callbacks'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/backend/base.rb:91:in `invoke_job'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/worker.rb:199:in `block (2 levels) in run'\", \"/var/vcap/packages/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'\", \"/var/vcap/packages/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:98:in `call'\", \"/var/vcap/packages/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:98:in `timeout'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/worker.rb:199:in `block in run'\", \"/var/vcap/packages/ruby-2.2.3/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/worker.rb:198:in `run'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/worker.rb:275:in `block in reserve_and_run_one_job'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/lifecycle.rb:61:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/lifecycle.rb:61:in `block in initialize'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/lifecycle.rb:66:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/lifecycle.rb:66:in `execute'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/lifecycle.rb:40:in `run_callbacks'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/worker.rb:275:in `reserve_and_run_one_job'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/worker.rb:182:in `block in work_off'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/worker.rb:181:in `times'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/worker.rb:181:in `work_off'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/worker.rb:146:in `block (4 levels) in start'\", \"/var/vcap/packages/ruby-2.2.3/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/worker.rb:145:in `block (3 levels) in start'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/lifecycle.rb:61:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/lifecycle.rb:61:in `block in initialize'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/lifecycle.rb:66:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/lifecycle.rb:66:in `execute'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/lifecycle.rb:40:in `run_callbacks'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/worker.rb:144:in `block (2 levels) in start'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/worker.rb:143:in `loop'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/worker.rb:143:in `block in start'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/plugins/clear_locks.rb:7:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/lifecycle.rb:79:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/lifecycle.rb:61:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/lifecycle.rb:61:in `block in initialize'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/lifecycle.rb:79:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/lifecycle.rb:79:in `block in add'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/lifecycle.rb:66:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/lifecycle.rb:66:in `execute'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/lifecycle.rb:40:in `run_callbacks'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.4/lib/delayed/worker.rb:142:in `start'\", \"lib/tasks/jobs.rake:40:in `start_working'\", \"lib/tasks/jobs.rake:11:in `block (2 levels) in <top (required)>'\", \"/var/vcap/packages/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `call'\", \"/var/vcap/packages/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'\", \"/var/vcap/packages/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `each'\", \"/var/vcap/packages/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `execute'\", \"/var/vcap/packages/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'\", \"/var/vcap/packages/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'\", \"/var/vcap/packages/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'\", \"/var/vcap/packages/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'\", \"/var/vcap/packages/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'\", \"/var/vcap/packages/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'\", \"/var/vcap/packages/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `each'\", \"/var/vcap/packages/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'\", \"/var/vcap/packages/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'\", \"/var/vcap/packages/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'\", \"/var/vcap/packages/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'\", \"/var/vcap/packages/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'\", \"/var/vcap/packages/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:75:in `run'\", \"/var/vcap/packages/ruby-2.2.3/bin/rake:33:in `<main>'\"]}","log_level":"error","source":"cc.background","data":{},"thread_id":70193027185040,"fiber_id":70193051853720,"process_id":3264,"file":"/var/vcap/data/packages/cloud_controller_ng/405c21e6b5094a7e5d35868d44a6427e655e6d4d.1-1ffca2f9fcdb2df71a5ecdfee63fe4a27178542e/cloud_controller_ng/app/jobs/exception_catching_job.rb","lineno":24,"method":"log_error"}
```
