### ISSUE TITLE
Increase max_attempts for jobs uploading to blobstore

### ISSUE THREAD

**Issue by keymon** [cloudfoundry/cloud_controller_ng#631]
## Issue

Blobstore backend might fail (e.g. S3 rate limiting or similar), and it is expected that we client retries the operations.
## Steps to Reproduce

Using S3 as blobstore, if there is a error in S3 you might get these errors:

```
<14>2016-06-27T13:30:13.215645+00:00 10.0.16.58 vcap.cloud_controller_worker_ctl.stdout [job=api index=0] [Worker(cc_api_worker.api.0.2)] Job VCAP::CloudController::Jobs::ExceptionCatchingJob (id=601995) REMOVED permanently because of 1 consecutive failures
```

caused by:

```
           "code" => 10001,
    "description" => "end of file reached (EOFError)",
     "error_code" => "CF-SocketError",
      "backtrace" => [
        [  0] "/var/vcap/packages/ruby-2.2.4/lib/ruby/2.2.0/openssl/buffering.rb:182:in `sysread_nonblock'",
        [  1] "/var/vcap/packages/ruby-2.2.4/lib/ruby/2.2.0/openssl/buffering.rb:182:in `read_nonblock'",
        [  2] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/excon-0.48.0/lib/excon/socket.rb:45:in `readline'",
        [  3] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/excon-0.48.0/lib/excon/response.rb:62:in `parse'",
        [  4] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/excon-0.48.0/lib/excon/middlewares/response_parser.rb:6:in `response_call'",
        [  5] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/excon-0.48.0/lib/excon/connection.rb:389:in `response'",
        [  6] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/excon-0.48.0/lib/excon/connection.rb:253:in `request'",
        [  7] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/fog-core-1.36.0/lib/fog/core/connection.rb:81:in `request'",
        [  8] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/fog-xml-0.1.2/lib/fog/xml/connection.rb:9:in `request'",
        [  9] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/fog-aws-0.9.1/lib/fog/aws/storage.rb:611:in `_request'",
        [ 10] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/fog-aws-0.9.1/lib/fog/aws/storage.rb:606:in `request'",
        [ 11] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/fog-aws-0.9.1/lib/fog/aws/requests/storage/get_object.rb:57:in `get_object'",
        [ 12] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/fog-aws-0.9.1/lib/fog/aws/models/storage/files.rb:61:in `get'",
        [ 13] "/var/vcap/data/packages/cloud_controller_ng/99480351ce9399b5630cd5e27a3118702ac29281.1-9b51947a04ab28dbfa8b6246c62620137cc38217/cloud_controller_ng/lib/cloud_controller/blobstore/fog/fog_client.rb:37:in `block in download_from_blobstore'",
        [ 14] "/var/vcap/data/packages/cloud_controller_ng/99480351ce9399b5630cd5e27a3118702ac29281.1-9b51947a04ab28dbfa8b6246c62620137cc38217/cloud_controller_ng/lib/cloud_controller/blobstore/fog/fog_client.rb:36:in `open'",
        [ 15] "/var/vcap/data/packages/cloud_controller_ng/99480351ce9399b5630cd5e27a3118702ac29281.1-9b51947a04ab28dbfa8b6246c62620137cc38217/cloud_controller_ng/lib/cloud_controller/blobstore/fog/fog_client.rb:36:in `download_from_blobstore'",
        [ 16] "/var/vcap/data/packages/cloud_controller_ng/99480351ce9399b5630cd5e27a3118702ac29281.1-9b51947a04ab28dbfa8b6246c62620137cc38217/cloud_controller_ng/app/models/runtime/app_bits_package.rb:17:in `block (2 levels) in create'",
        [ 17] "/var/vcap/data/packages/cloud_controller_ng/99480351ce9399b5630cd5e27a3118702ac29281.1-9b51947a04ab28dbfa8b6246c62620137cc38217/cloud_controller_ng/lib/cloud_controller/blobstore/fingerprints_collection.rb:27:in `yield'",
        [ 18] "/var/vcap/data/packages/cloud_controller_ng/99480351ce9399b5630cd5e27a3118702ac29281.1-9b51947a04ab28dbfa8b6246c62620137cc38217/cloud_controller_ng/lib/cloud_controller/blobstore/fingerprints_collection.rb:27:in `block in each'",
        [ 19] "/var/vcap/data/packages/cloud_controller_ng/99480351ce9399b5630cd5e27a3118702ac29281.1-9b51947a04ab28dbfa8b6246c62620137cc38217/cloud_controller_ng/lib/cloud_controller/blobstore/fingerprints_collection.rb:26:in `each'",
        [ 20] "/var/vcap/data/packages/cloud_controller_ng/99480351ce9399b5630cd5e27a3118702ac29281.1-9b51947a04ab28dbfa8b6246c62620137cc38217/cloud_controller_ng/lib/cloud_controller/blobstore/fingerprints_collection.rb:26:in `each'",
        [ 21] "/var/vcap/data/packages/cloud_controller_ng/99480351ce9399b5630cd5e27a3118702ac29281.1-9b51947a04ab28dbfa8b6246c62620137cc38217/cloud_controller_ng/app/models/runtime/app_bits_package.rb:16:in `block in create'",
        [ 22] "/var/vcap/data/packages/cloud_controller_ng/99480351ce9399b5630cd5e27a3118702ac29281.1-9b51947a04ab28dbfa8b6246c62620137cc38217/cloud_controller_ng/lib/cloud_controller/blobstore/local_app_bits.rb:18:in `yield'",
        [ 23] "/var/vcap/data/packages/cloud_controller_ng/99480351ce9399b5630cd5e27a3118702ac29281.1-9b51947a04ab28dbfa8b6246c62620137cc38217/cloud_controller_ng/lib/cloud_controller/blobstore/local_app_bits.rb:18:in `block in from_compressed_bits'",
        [ 24] "/var/vcap/packages/ruby-2.2.4/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'",
        [ 25] "/var/vcap/data/packages/cloud_controller_ng/99480351ce9399b5630cd5e27a3118702ac29281.1-9b51947a04ab28dbfa8b6246c62620137cc38217/cloud_controller_ng/lib/cloud_controller/blobstore/local_app_bits.rb:11:in `from_compressed_bits'",
        [ 26] "/var/vcap/data/packages/cloud_controller_ng/99480351ce9399b5630cd5e27a3118702ac29281.1-9b51947a04ab28dbfa8b6246c62620137cc38217/cloud_controller_ng/app/models/runtime/app_bits_package.rb:11:in `create'",
        [ 27] "/var/vcap/data/packages/cloud_controller_ng/99480351ce9399b5630cd5e27a3118702ac29281.1-9b51947a04ab28dbfa8b6246c62620137cc38217/cloud_controller_ng/app/jobs/runtime/app_bits_packer.rb:28:in `perform'",
        [ 28] "/var/vcap/data/packages/cloud_controller_ng/99480351ce9399b5630cd5e27a3118702ac29281.1-9b51947a04ab28dbfa8b6246c62620137cc38217/cloud_controller_ng/app/jobs/wrapping_job.rb:9:in `perform'",
        [ 29] "/var/vcap/data/packages/cloud_controller_ng/99480351ce9399b5630cd5e27a3118702ac29281.1-9b51947a04ab28dbfa8b6246c62620137cc38217/cloud_controller_ng/app/jobs/timeout_job.rb:7:in `block in perform'",
        [ 30] "/var/vcap/packages/ruby-2.2.4/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'",
        [ 31] "/var/vcap/packages/ruby-2.2.4/lib/ruby/2.2.0/timeout.rb:32:in `block in catch'",
        [ 32] "/var/vcap/packages/ruby-2.2.4/lib/ruby/2.2.0/timeout.rb:32:in `catch'",
        [ 33] "/var/vcap/packages/ruby-2.2.4/lib/ruby/2.2.0/timeout.rb:32:in `catch'",
        [ 34] "/var/vcap/packages/ruby-2.2.4/lib/ruby/2.2.0/timeout.rb:103:in `timeout'",
        [ 35] "/var/vcap/data/packages/cloud_controller_ng/99480351ce9399b5630cd5e27a3118702ac29281.1-9b51947a04ab28dbfa8b6246c62620137cc38217/cloud_controller_ng/app/jobs/timeout_job.rb:6:in `perform'",
        [ 36] "/var/vcap/data/packages/cloud_controller_ng/99480351ce9399b5630cd5e27a3118702ac29281.1-9b51947a04ab28dbfa8b6246c62620137cc38217/cloud_controller_ng/app/jobs/request_job.rb:13:in `perform'",
        [ 37] "/var/vcap/data/packages/cloud_controller_ng/99480351ce9399b5630cd5e27a3118702ac29281.1-9b51947a04ab28dbfa8b6246c62620137cc38217/cloud_controller_ng/app/jobs/wrapping_job.rb:9:in `perform'",
        [ 38] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:94:in `block in invoke_job'",
        [ 39] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'",
        [ 40] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'",
        [ 41] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'",
        [ 42] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'",
        [ 43] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'",
        [ 44] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:91:in `invoke_job'",
        [ 45] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block (2 levels) in run'",
        [ 46] "/var/vcap/packages/ruby-2.2.4/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'",
        [ 47] "/var/vcap/packages/ruby-2.2.4/lib/ruby/2.2.0/timeout.rb:98:in `call'",
        [ 48] "/var/vcap/packages/ruby-2.2.4/lib/ruby/2.2.0/timeout.rb:98:in `timeout'",
        [ 49] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block in run'",
        [ 50] "/var/vcap/packages/ruby-2.2.4/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'",
        [ 51] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:203:in `run'",
        [ 52] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `block in reserve_and_run_one_job'",
        [ 53] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'",
        [ 54] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'",
        [ 55] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'",
        [ 56] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'",
        [ 57] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'",
        [ 58] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `reserve_and_run_one_job'",
        [ 59] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:187:in `block in work_off'",
        [ 60] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `times'",
        [ 61] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `work_off'",
        [ 62] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:150:in `block (4 levels) in start'",
        [ 63] "/var/vcap/packages/ruby-2.2.4/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'",
        [ 64] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:149:in `block (3 levels) in start'",
        [ 65] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'",
        [ 66] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'",
        [ 67] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'",
        [ 68] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'",
        [ 69] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'",
        [ 70] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:148:in `block (2 levels) in start'",
        [ 71] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `loop'",
        [ 72] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `block in start'",
        [ 73] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `call'",
        [ 74] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'",
        [ 75] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'",
        [ 76] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'",
        [ 77] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'",
        [ 78] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'",
        [ 79] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'",
        [ 80] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block in add'",
        [ 81] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'",
        [ 82] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'",
        [ 83] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'",
        [ 84] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:146:in `start'",
        [ 85] "/var/vcap/data/packages/cloud_controller_ng/99480351ce9399b5630cd5e27a3118702ac29281.1-9b51947a04ab28dbfa8b6246c62620137cc38217/cloud_controller_ng/lib/tasks/jobs.rake:40:in `start_working'",
        [ 86] "/var/vcap/data/packages/cloud_controller_ng/99480351ce9399b5630cd5e27a3118702ac29281.1-9b51947a04ab28dbfa8b6246c62620137cc38217/cloud_controller_ng/lib/tasks/jobs.rake:11:in `block (2 levels) in <top (required)>'",
        [ 87] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'",
        [ 88] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'",
        [ 89] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'",
        [ 90] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'",
        [ 91] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'",
        [ 92] "/var/vcap/packages/ruby-2.2.4/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'",
        [ 93] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'",
        [ 94] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'",
        [ 95] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'",
        [ 96] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'",
        [ 97] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'",
        [ 98] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'",
        [ 99] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'",
        [100] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'",
        [101] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'",
        [102] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'",
        [103] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'",
        [104] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'",
        [105] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/bin/rake:23:in `load'",
        [106] "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/bin/rake:23:in `<main>'"
    ]
```
## Expected result

The operation can be retried some times.
## Current result

The job fails with the first retry, making the deployment fail.
## Possible Fix

Cloudcontroller implements logic to retry some tasks by using the [`delayed_job` library](https://github.com/collectiveidea/delayed_job), but several jobs [set the `max_attempts` to 1](https://github.com/cloudfoundry/cloud_controller_ng/blob/ffab2aa456f8ad4a595952f2a2475c70bd6c7cb2/app/jobs/runtime/app_bits_packer.rb).

I think we can increase the number of `max_attempts` to 3 for some of these jobs:
- app/jobs/runtime/buildpack_installer.rb
- app/jobs/runtime/droplet_upload.rb
- app/jobs/runtime/app_bits_packer.rb
- app/jobs/runtime/app_bits_copier.rb
- app/jobs/v3/package_bits_copier.rb
- app/jobs/v3/package_bits.rb
- app/jobs/v3/droplet_bits_copier.rb

Otherwise maybe we can do it in the fog library or in the client.

**Comment by dcarley** [comment]
An example of the errors we've seen from [cf-acceptance-tests](https://github.com/cloudfoundry/cf-acceptance-tests) with some details redacted:
```
[2016-06-15 13:32:40.24 (UTC)]> cf push CATS-APP-d627ba08-584f-4500-47ee-9da73213529e --no-start -b ruby_buildpack -m 256M -p ../assets/dora -d REDACTED
Creating app CATS-APP-d627ba08-584f-4500-47ee-9da73213529e in org CATS-ORG-1-2016_06_15-13h24m10.923s / space CATS-SPACE-1-2016_06_15-13h24m10.923s as CATS-USER-1-2016_06_15-13h24m10.923s...
OK

Creating route cats-app-d627ba08-584f-4500-47ee-9da73213529e.REDACTED...
OK

Binding cats-app-d627ba08-584f-4500-47ee-9da73213529e.REDACTED to CATS-APP-d627ba08-584f-4500-47ee-9da73213529e...
OK

Uploading CATS-APP-d627ba08-584f-4500-47ee-9da73213529e...
Uploading app files from: /tmp/build/f541ec31/cf-release/src/github.com/cloudfoundry/cf-acceptance-tests/assets/dora
Uploading 182.9K, 37 files
Done uploading               
FAILED
Error uploading application.
An unknown error occurred.
```

**Comment by adowns01** [comment]
Hello @keymon, 

Thanks for bringing this to our attention. We just merged this [PR] (https://github.com/cloudfoundry/cloud_controller_ng/pull/628) which will retry on S3 flakes. We also have a [story](https://www.pivotaltracker.com/story/show/121630281) in our backlog to add more retries around accessing our blobstore. 

Is there anything else you can recommend before closing this issue?

Thanks,
@adowns01 && @youreddy

**Comment by michaelxupiv** [comment]
Hey @keymon ,

We have added retries to our clients and blob objects as of #124923231. Thanks for exposing the issue, please let us know if there is anything else we can do. Closing this for now.

Thanks,
@michaelxupiv
