### ISSUE TITLE
cloud_controller_clock doesn't appear to recover well from connection error when in HA mode

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cloud_controller_ng#766]
## Issue
When running cloud_controller_clock in HA mode it appears that the database can get into a state where the node can never again acquire a lock without restarting the database instance.

## Context

We recently deployed CF v251.  As part of this deploy we moved cloud_controller_clock into an HA situation (2 nodes).  We started noticing that in several of our environments the second node (not sure why it is always the second node coincidence???) will occasionally get into a state where it continually times out attempting to get a transaction lock. (See error below)  When in this state it appears the only way to fix it is to restart the mysql node in the cluster that everyone is connecting to.

It appears one way to get into this state is for a mysql connection hiccup to take place.  In our case a "Mysql2::Error: MySQL server has gone away" error that we occasionally get in our environment.

Snippet of cloud_controller_clock.log showing working then not working:
```
{"timestamp":1485678777.0087678,"message":"Queueing VCAP::CloudController::Jobs::Diego::Sync at 2017-01-29 08:32:57 UTC","log_level":"info","source":"cc.clock","data":{},"thread_id":47119212114180,"fiber_id":47119256004640,"process_id":29099,"file":"/var/vcap/data/packages/cloud_controller_ng/aa586e54ee45aa382a0d5ebbab32e1c8aa048953.1-1bb43f159f71d158a13148b68b5c6468b52d4b25/cloud_controller_ng/lib/cloud_controller/clock.rb","lineno":25,"method":"block in schedule_frequent_job"}
{"timestamp":1485678807.0017111,"message":"Queueing VCAP::CloudController::Jobs::Diego::Sync at 2017-01-29 08:33:27 UTC","log_level":"info","source":"cc.clock","data":{},"thread_id":47119212114180,"fiber_id":47119256004640,"process_id":29099,"file":"/var/vcap/data/packages/cloud_controller_ng/aa586e54ee45aa382a0d5ebbab32e1c8aa048953.1-1bb43f159f71d158a13148b68b5c6468b52d4b25/cloud_controller_ng/lib/cloud_controller/clock.rb","lineno":25,"method":"block in schedule_frequent_job"}
{"timestamp":1485678826.116222,"message":"Mysql2::Error: MySQL server has gone away: ROLLBACK","log_level":"error","source":"cc.background","data":{},"thread_id":47119212114180,"fiber_id":47119256004640,"process_id":29099,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/database/logging.rb","lineno":87,"method":"block in log_each"}
{"timestamp":1485678930.9480402,"message":"Mysql2::Error: Lock wait timeout exceeded; try restarting transaction: SELECT * FROM `lockings` WHERE (`id` = 4) LIMIT 1 FOR UPDATE","log_level":"error","source":"cc.background","data":{},"thread_id":47220685672740,"fiber_id":47220727248080,"process_id":8465,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/database/logging.rb","lineno":87,"method":"block in log_each"}
{"timestamp":1485678990.953872,"message":"Mysql2::Error: Lock wait timeout exceeded; try restarting transaction: SELECT * FROM `lockings` WHERE (`id` = 4) LIMIT 1 FOR UPDATE","log_level":"error","source":"cc.background","data":{},"thread_id":46923952001300,"fiber_id":46923995927420,"process_id":9224,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/database/logging.rb","lineno":87,"method":"block in log_each"}
{"timestamp":1485679051.9586556,"message":"Mysql2::Error: Lock wait timeout exceeded; try restarting transaction: SELECT * FROM `lockings` WHERE (`id` = 4) LIMIT 1 FOR UPDATE","log_level":"error","source":"cc.background","data":{},"thread_id":47198106136840,"fiber_id":47198150047220,"process_id":9918,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/database/logging.rb","lineno":87,"method":"block in log_each"}
```

Lock timeout error in cloud_controller_clock_ctl.err.log repeated until mysql node is restarted
```
[2017-01-29 16:01:06+0000] ------------ STARTING cloud_controller_clock_ctl at Sun Jan 29 16:01:06 UTC 2017 --------------
[2017-01-29 16:02:00+0000] rake aborted!
[2017-01-29 16:02:00+0000] Sequel::DatabaseError: Mysql2::Error: Lock wait timeout exceeded; try restarting transaction
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `_query'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `block in query'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `handle_interrupt'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `query'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/adapters/mysql2.rb:136:in `block in _execute'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/database/logging.rb:48:in `log_connection_yield'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/adapters/mysql2.rb:131:in `_execute'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/adapters/utils/mysql_mysql2.rb:36:in `block in execute'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/database/connecting.rb:280:in `block in synchronize'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/connection_pool/threaded.rb:103:in `hold'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/database/connecting.rb:280:in `synchronize'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/adapters/utils/mysql_mysql2.rb:36:in `execute'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/dataset/actions.rb:970:in `execute'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/adapters/mysql2.rb:296:in `execute'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/adapters/mysql2.rb:255:in `fetch_rows'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/dataset/actions.rb:853:in `with_sql_each'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/dataset/actions.rb:861:in `with_sql_first'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/dataset/actions.rb:664:in `single_record!'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/dataset/actions.rb:652:in `single_record'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/dataset/actions.rb:194:in `first'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/model/base.rb:2017:in `_refresh_get'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/model/base.rb:2011:in `_refresh'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/model/base.rb:1526:in `lock!'
[2017-01-29 16:02:00+0000] /var/vcap/data/packages/cloud_controller_ng/aa586e54ee45aa382a0d5ebbab32e1c8aa048953.1-1bb43f159f71d158a13148b68b5c6468b52d4b25/cloud_controller_ng/lib/cloud_controller/scheduler.rb:25:in `block in start'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/database/transactions.rb:215:in `_transaction'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/database/transactions.rb:190:in `block in transaction'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/database/connecting.rb:280:in `block in synchronize'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/database/connecting.rb:280:in `synchronize'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/database/transactions.rb:156:in `transaction'
[2017-01-29 16:02:00+0000] /var/vcap/data/packages/cloud_controller_ng/aa586e54ee45aa382a0d5ebbab32e1c8aa048953.1-1bb43f159f71d158a13148b68b5c6468b52d4b25/cloud_controller_ng/lib/cloud_controller/scheduler.rb:24:in `start'
[2017-01-29 16:02:00+0000] /var/vcap/data/packages/cloud_controller_ng/aa586e54ee45aa382a0d5ebbab32e1c8aa048953.1-1bb43f159f71d158a13148b68b5c6468b52d4b25/cloud_controller_ng/lib/tasks/clock.rake:8:in `block (2 levels) in <top (required)>
'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
[2017-01-29 16:02:00+0000] /var/vcap/packages/ruby-2.3/bin/bundle:22:in `load'
[2017-01-29 16:02:00+0000] /var/vcap/packages/ruby-2.3/bin/bundle:22:in `<main>'
[2017-01-29 16:02:00+0000] Mysql2::Error: Lock wait timeout exceeded; try restarting transaction
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `_query'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `block in query'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `handle_interrupt'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `query'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/adapters/mysql2.rb:136:in `block in _execute'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/database/logging.rb:48:in `log_connection_yield'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/adapters/mysql2.rb:131:in `_execute'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/adapters/utils/mysql_mysql2.rb:36:in `block in execute'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/database/connecting.rb:280:in `block in synchronize'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/connection_pool/threaded.rb:103:in `hold'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/database/connecting.rb:280:in `synchronize'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/adapters/utils/mysql_mysql2.rb:36:in `execute'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/dataset/actions.rb:970:in `execute'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/adapters/mysql2.rb:296:in `execute'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/adapters/mysql2.rb:255:in `fetch_rows'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/dataset/actions.rb:853:in `with_sql_each'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/dataset/actions.rb:861:in `with_sql_first'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/dataset/actions.rb:664:in `single_record!'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/dataset/actions.rb:652:in `single_record'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/dataset/actions.rb:194:in `first'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/model/base.rb:2017:in `_refresh_get'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/model/base.rb:2011:in `_refresh'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/model/base.rb:1526:in `lock!'
[2017-01-29 16:02:00+0000] /var/vcap/data/packages/cloud_controller_ng/aa586e54ee45aa382a0d5ebbab32e1c8aa048953.1-1bb43f159f71d158a13148b68b5c6468b52d4b25/cloud_controller_ng/lib/cloud_controller/scheduler.rb:25:in `block in start'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/database/transactions.rb:215:in `_transaction'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/database/transactions.rb:190:in `block in transaction'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/database/connecting.rb:280:in `block in synchronize'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/database/connecting.rb:280:in `synchronize'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.41.0/lib/sequel/database/transactions.rb:156:in `transaction'
[2017-01-29 16:02:00+0000] /var/vcap/data/packages/cloud_controller_ng/aa586e54ee45aa382a0d5ebbab32e1c8aa048953.1-1bb43f159f71d158a13148b68b5c6468b52d4b25/cloud_controller_ng/lib/cloud_controller/scheduler.rb:24:in `start'
[2017-01-29 16:02:00+0000] /var/vcap/data/packages/cloud_controller_ng/aa586e54ee45aa382a0d5ebbab32e1c8aa048953.1-1bb43f159f71d158a13148b68b5c6468b52d4b25/cloud_controller_ng/lib/tasks/clock.rake:8:in `block (2 levels) in <top (required)>
'
[2017-01-29 16:02:00+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
[2017-01-29 16:02:00+0000] /var/vcap/packages/ruby-2.3/bin/bundle:22:in `load'
[2017-01-29 16:02:00+0000] /var/vcap/packages/ruby-2.3/bin/bundle:22:in `<main>'
[2017-01-29 16:02:00+0000] Tasks: TOP => clock:start
[2017-01-29 16:02:00+0000] (See full trace by running task with --trace)
[2017-01-29 16:02:07+0000] ------------ STARTING cloud_controller_clock_ctl at Sun Jan 29 16:02:07 UTC 2017 --------------
```

## Steps to Reproduce

I haven't tried hard to reliably reproduce this yet, but one thing you can try is reproducing a "Mysql has gone away" error.  Perhaps with an iptables rule?  You also might have better luck if you're connecting to a specific mysql node instead of to a load balancer though I haven't yet confirmed if this messes up the cluster or just a single node.

## Expected result

cloud_controller_clock on the second node would eventually recover and be able to aquire a lock again.

## Current result

Fails to acquire a lock forever until I restart the database node it is connecting to.

**Comment by youngm** [comment]
Forgot to mention I'm using the cf-mysql release version 32.1 in a 3 node cluster.

**Comment by zrob** [comment]
@youngm I suspect this just means that the other node picked up the lock and this one is cycling through attempts to acquire the lock while the other node is chugging away.  So possibly "working as intended"

It's definitely off-putting to see this in the logs however if things are actually working properly.  We'll take a closer look to make sure things are working properly and that it's not so noisy.

**Comment by youngm** [comment]
@zrob That is a possibility.  That is what I thought at first.  The thing that threw me off is that after I reboot the mysql node both cloud_controller_clock nodes appear to log healthy both kicking off jobs again and that is they wall all my installations appear now.

Next time I see this issue I'll try shutting off the working node and see if the other node begins working normally.

**Comment by aashah** [comment]
Hey @youngm,

We looked at our own CI environment and found similar logs. The clock functionality still seems to be present, but like Zach mentioned we're not happy with a healthy system having such spammy logs. Nor should the other clock failing be a good thing. We currently believe the initial "Mysql2::Error: MySQL server has gone away" is due to mysql killing our long-running, with no activity, lock. The following frequent thrashing from the clock is unclear still.

We're looking at how this manifests with a CC hooked up to postgres. And then hopefully we'll have a better solution.

- Aakash & @michaelxupiv

**Comment by utako** [comment]
Hello @youngm,

We were able to reproduce this error, and we see that it is a result of the [`innodb_lock_wait_timeout`](https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_lock_wait_timeout). We did not observe this with Postgres, because it defaults to [no `lock_timeout`](https://www.postgresql.org/docs/9.3/static/runtime-config-client.html). 

For these reasons, we believe the clock is mostly functioning as intended, but we've gone ahead and added some logging and a loop to ensure that clocks unable to acquire a lock will retry without stopping the clock monit process. You can follow the [tracker story](https://www.pivotaltracker.com/story/show/138651527).

Thanks for bringing this to our attention,
@utako and @aashah, CF CAPI Team

**Comment by youngm** [comment]
Sounds good.  Thanks @utako !

Mike
