### ISSUE TITLE
If CC is slow to start, it will crash with 'Authorization Timeout' (NATS::AuthError)

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/cloud_controller_ng#797]
## Version

capi-release 1.23.0

## Issue

While testing against a database in another network (GCP VM -> Azure DB), our API job would crash with 'Authorization Timeout' (NATS::AuthError). From the [NATS docs](https://nats.io/documentation/internals/nats-protocol/), this error is caused by the client initiating a connection but then taking too long to follow up with an authentication request. The nats-release defaults this timeout to 15 seconds, which should have been more than enough. While debugging we noticed that [Line 81](https://github.com/cloudfoundry/cloud_controller_ng/blob/e1bea701d26ddeea2ca1ad523004e4ac295d3e83/lib/cloud_controller/runner.rb#L79-L81) (`start_cloud_controller`) took about 15 seconds, then the Auth Timeout was caught while inside the EventMachine loop.

We speculate that we might be misusing EventMachine and the blocking `start_cloud_controller` call is blocking the NATS client from sending the authentication request until after the Auth Timeout has expired.

## Workaround

Bump the NATS timeout under `instance_groups.nats.jobs.nats.properties.nats.authorization_timeout: 30`.

## Stack Trace

From `/var/vcap/sys/log/cloud_controller_ng/cloud_controller_ng_ctl.err.log`:
```
[2017-03-23 17:14:01+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/cache/ruby-nats-8571cf9d685b/lib/nats/client.rb:645:in `block in connection_completed': 'Authorization Timeout' (NATS::AuthError)
[2017-03-23 17:14:01+0000]      from /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/cache/ruby-nats-8571cf9d685b/lib/nats/client.rb:559:in `receive_data'
[2017-03-23 17:14:01+0000]      from /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
[2017-03-23 17:14:01+0000]      from /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
[2017-03-23 17:14:01+0000]      from /var/vcap/data/packages/cloud_controller_ng/d23c1d1f81ed3423ed8924aa68d2aa6bf87b0c4e/cloud_controller_ng/lib/cloud_controller/runner.rb:77:in `run!'
[2017-03-23 17:14:01+0000]      from /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/bin/cloud_controller:8:in `<main>'
```

**Comment by mikexuu** [comment]
Hey @ljfranklin ,

Thanks for submitting this issue! Sorry we didn't get to this sooner, but good news: we (and probably you) are currently working on a story to remove this troubling NATS connection entirely (https://www.pivotaltracker.com/story/show/146109969) . Closing this for now as this will get resolved as of next capi-release. 

Best,
CAPI Community Pair - @matt-royal && @mikexuu
